SELECT 
  SOQ.CREDAT_0 AS 'DATE CREATED',
  CASE 
    WHEN SOH.SHIDAT_0 > GETDATE() THEN 'FUTURE DELIVERY' 
    WHEN SOQ.ALLQTY_0 < STK.SUM_STOCK THEN 'UNALLOCATED'
    ELSE 'BACKORDERED'
  END AS 'LINE STATUS',
  SOQ.SOHNUM_0 AS 'ORDER', 
  SOH.CUSORDREF_0 AS 'PO', 
  CASE WHEN SOH.BETFCY_0 = 1 THEN 'SALES' ELSE 'INTERSITE' END AS 'TYPE', 
  SOH.HLDCOD_0 AS 'ORDER HOLD', 
  SOH.STOFCY_0 AS 'STOCK SITE', 
  SOH.BPCORD_0 AS 'CUSTOMER',
  SOH.BPCNAM_0 AS 'CUSTOMER NAME', 
  SOQ.ITMREF_0 AS 'PRODUCT', 
  ITM.ITMDES1_0 + ' ' + ITM.ITMDES2_0 + ' ' + ITM.ITMDES3_0 AS 'DESCRIPTION', 
  ITM.TSICOD_0 AS 'STATUS', 
  CASE ITF.ABCCLS_0 WHEN 1 THEN 'A' WHEN 2 THEN 'B' WHEN 3 THEN 'C' WHEN 4 THEN 'D' ELSE 'UNRANKED' END AS 'ABC CLASS', 
  CASE WHEN ITM2.ITMREF_0 IS NULL THEN 'N/A' ELSE ITM2.ITMREF_0 END AS 'ALTERNATIVE', 
  CASE WHEN ITM2.ITMDES1_0 + ' ' + ITM.ITMDES2_0 + ' ' + ITM.ITMDES3_0 IS NULL THEN 'N/A' ELSE ITM2.ITMDES1_0 + ' ' + ITM.ITMDES2_0 + ' ' + ITM.ITMDES3_0 END AS 'ALT DESCRIPTION', 
  SOQ.QTY_0 AS 'ORDERED', 
  SOQ.QTY_0 - (SOQ.DLVQTY_0 + SOQ.OPRQTY_0) AS 'REMAINING', 
  SOQ.ALLQTY_0 AS 'ALLOCATED', 
  isnull(STK.DC30,0) AS 'DC30 OH', 
  isnull(STK.DC33,0) AS 'DC33 OH',
  isnull(STK.[1600],0) AS 'COURT. OH', 
  isnull(STK.[2100],0) AS 'FORT OH', 
  isnull(STK.[2200],0) AS 'OAK OH', 
  isnull(STK.[2300],0) AS 'BROAD OH', 
  isnull(STK.[2600],0) AS 'SIDNEY OH',
  ISNULL(STK.SUM_STOCK,0),
  PO.EARLIEST_PO, 
  PO.ETA, 
  PO.PO_VENDOR, 
  ITP.PRIO_VENDOR, 
  ITP.MOQ, 
  ISNULL(SALES.DC30_SALES_1M,0), 
  ISNULL(SALES.DC30_SALES_3M,0), 
  ISNULL(SALES.DC30_SALES_12M,0), 
  ISNULL(SALES.DC33_SALES_1M,0), 
  ISNULL(SALES.DC33_SALES_3M,0), 
  ISNULL(SALES.DC33_SALES_12M,0), 
  ISNULL(SALES.ALL_SALES_1M,0), 
  ISNULL(SALES.ALL_SALES_3M,0), 
  ISNULL(SALES.ALL_SALES_12M,0), 
  ISNULL(SALES.RETAIL_SALES_1M,0), 
  ISNULL(SALES.RETAIL_SALES_3M,0), 
  ISNULL(SALES.RETAIL_SALES_12M,0)
FROM 
  LIVE.SORDERQ SOQ 
  LEFT OUTER JOIN LIVE.SORDER SOH ON SOQ.SOHNUM_0 = SOH.SOHNUM_0 
  LEFT OUTER JOIN LIVE.ITMMASTER ITM ON SOQ.ITMREF_0 = ITM.ITMREF_0 
  LEFT OUTER JOIN LIVE.ITMMASTER ITM2 ON ITM.RPLITM_0 = ITM2.ITMREF_0 
  LEFT OUTER JOIN LIVE.ITMFACILIT ITF ON SOQ.STOFCY_0 = ITF.STOFCY_0 AND SOQ.ITMREF_0 = ITF.ITMREF_0 
  LEFT OUTER JOIN (
    SELECT 
      ITMREF_0,
      SUM(CASE WHEN STOFCY_0 = 'DC30' THEN QTYSTU_0 - CUMALLQTY_0 ELSE 0 END) AS DC30,
      SUM(CASE WHEN STOFCY_0 = 'DC33' THEN QTYSTU_0 - CUMALLQTY_0 ELSE 0 END) AS DC33,
      SUM(CASE WHEN STOFCY_0 = '1600' THEN QTYSTU_0 - CUMALLQTY_0 ELSE 0 END) AS [1600],
      SUM(CASE WHEN STOFCY_0 = '2100' THEN QTYSTU_0 - CUMALLQTY_0 ELSE 0 END) AS [2100],
      SUM(CASE WHEN STOFCY_0 = '2200' THEN QTYSTU_0 - CUMALLQTY_0 ELSE 0 END) AS [2200],
      SUM(CASE WHEN STOFCY_0 = '2300' THEN QTYSTU_0 - CUMALLQTY_0 ELSE 0 END) AS [2300],
      SUM(CASE WHEN STOFCY_0 = '2600' THEN QTYSTU_0 - CUMALLQTY_0 ELSE 0 END) AS [2600],
	  SUM(QTYSTU_0 - CUMALLQTY_0) AS SUM_STOCK
    FROM 
      LIVE.STOCK 
    WHERE 
      STA_0 = 'A'
    GROUP BY 
      ITMREF_0
  ) STK ON SOQ.ITMREF_0 = STK.ITMREF_0
  LEFT OUTER JOIN (
    SELECT 
      ITMREF_0,
      MAX(CASE WHEN LEFT(POHNUM_0,3)='PO3' AND LEFT(BPS.BPSNUM_0,1)='V' AND LINCLEFLG_0 = 1 THEN POHNUM_0 ELSE NULL END) AS EARLIEST_PO,
      MAX(CASE WHEN LEFT(POHNUM_0,3)='PO3' AND LEFT(BPS.BPSNUM_0,1)='V' AND LINCLEFLG_0 = 1 THEN EXTRCPDAT_0 ELSE NULL END) AS ETA,
      MAX(CASE WHEN LEFT(POHNUM_0,3)='PO3' AND LEFT(BPS.BPSNUM_0,1)='V' AND LINCLEFLG_0 = 1 THEN BPSNAM_0 + ' - ' + BPS.BPSNUM_0 ELSE NULL END) AS PO_VENDOR
    FROM 
      LIVE.PORDERQ POQ 
      LEFT OUTER JOIN LIVE.BPSUPPLIER BPS ON POQ.BPSNUM_0 = BPS.BPSNUM_0 
    GROUP BY 
      ITMREF_0
  ) PO ON SOQ.ITMREF_0 = PO.ITMREF_0
  LEFT OUTER JOIN (
    SELECT 
      ITMREF_0,
      MAX(BPS.BPSNAM_0 + ' - ' + ITP.BPSNUM_0) AS PRIO_VENDOR,
      MAX(PURMINQTY_0) AS MOQ
    FROM 
      LIVE.ITMBPS ITP 
      LEFT OUTER JOIN LIVE.BPSUPPLIER BPS ON ITP.BPSNUM_0 = BPS.BPSNUM_0 
    GROUP BY 
      ITMREF_0
  ) ITP ON SOQ.ITMREF_0 = ITP.ITMREF_0
  LEFT OUTER JOIN (
    SELECT 
      ITMREF_0,
      SUM(CASE WHEN STOFCY_0 = 'DC30' AND CREDAT_0 >= DATEADD(MONTH, -1, GETDATE()) THEN AMTNOTLIN_0 ELSE 0 END) AS DC30_SALES_1M,
      SUM(CASE WHEN STOFCY_0 = 'DC30' AND CREDAT_0 >= DATEADD(MONTH, -3, GETDATE()) THEN AMTNOTLIN_0 ELSE 0 END) AS DC30_SALES_3M,
      SUM(CASE WHEN STOFCY_0 = 'DC30' AND CREDAT_0 >= DATEADD(MONTH, -12, GETDATE()) THEN AMTNOTLIN_0 ELSE 0 END) AS DC30_SALES_12M,
      SUM(CASE WHEN STOFCY_0 = 'DC33' AND CREDAT_0 >= DATEADD(MONTH, -1, GETDATE()) THEN AMTNOTLIN_0 ELSE 0 END) AS DC33_SALES_1M,
      SUM(CASE WHEN STOFCY_0 = 'DC33' AND CREDAT_0 >= DATEADD(MONTH, -3, GETDATE()) THEN AMTNOTLIN_0 ELSE 0 END) AS DC33_SALES_3M,
      SUM(CASE WHEN STOFCY_0 = 'DC33' AND CREDAT_0 >= DATEADD(MONTH, -12, GETDATE()) THEN AMTNOTLIN_0 ELSE 0 END) AS DC33_SALES_12M,
      SUM(CASE WHEN CREDAT_0 >= DATEADD(MONTH, -1, GETDATE()) THEN AMTNOTLIN_0 ELSE 0 END) AS ALL_SALES_1M,
      SUM(CASE WHEN CREDAT_0 >= DATEADD(MONTH, -3, GETDATE()) THEN AMTNOTLIN_0 ELSE 0 END) AS ALL_SALES_3M,
      SUM(CASE WHEN CREDAT_0 >= DATEADD(MONTH, -12, GETDATE()) THEN AMTNOTLIN_0 ELSE 0 END) AS ALL_SALES_12M,
      SUM(CASE WHEN LEFT(STOFCY_0,2)<>'DC' AND CREDAT_0 >= DATEADD(MONTH, -1, GETDATE()) THEN AMTNOTLIN_0 ELSE 0 END) AS RETAIL_SALES_1M,
      SUM(CASE WHEN LEFT(STOFCY_0,2)<>'DC' AND CREDAT_0 >= DATEADD(MONTH, -3, GETDATE()) THEN AMTNOTLIN_0 ELSE 0 END) AS RETAIL_SALES_3M,
      SUM(CASE WHEN LEFT(STOFCY_0,2)<>'DC' AND CREDAT_0 >= DATEADD(MONTH, -12, GETDATE()) THEN AMTNOTLIN_0 ELSE 0 END) AS RETAIL_SALES_12M
    FROM 
      LIVE.SINVOICED 
    GROUP BY 
      ITMREF_0
  ) SALES ON SOQ.ITMREF_0 = SALES.ITMREF_0
WHERE 
  SOQ.SOQSTA_0 <> 3 
  AND LEFT(SOQ.ITMREF_0,1)<>'/' 
  AND (SOQ.QTYSTU_0 - (SOQ.ALLQTYSTU_0 + SOQ.PREQTYSTU_0 + SOQ.DLVQTYSTU_0) > 0 
  AND SOQ.QTYSTU_0 - (SOQ.ALLQTYSTU_0 + SOQ.OPRQTYSTU_0 + SOQ.TDLQTYSTU_0) > 0
  AND SOQ.QTYSTU_0 - (SOQ.ALLQTYSTU_0 + SOQ.PREQTYSTU_0 + SOQ.TDLQTYSTU_0) > 0)
  AND SOQ.BPCORD_0 IN ('ICR53','ICR54','ICR55','ICR56','ICR57','ICR58','ICR59','ICR60','ICR61','ICR62','ICR63','1200','1300','1400','1500','1600','1700','1800','1900','2000','2100','2200','2300','2400','2500','2600','2700','2800','IDC30','IDC31','IDC33','IDC52')
GROUP BY 
  SOQ.CREDAT_0, 
  SOQ.SOHNUM_0, 
  SOH.CUSORDREF_0, 
  SOH.STOFCY_0, 
  SOH.BPCORD_0, 
  SOH.BPCNAM_0, 
  SOQ.ITMREF_0, 
  ITM.TSICOD_0, 
  ITM.ITMDES1_0, 
  ITM.ITMDES2_0, 
  ITM.ITMDES3_0, 
  ITF.ABCCLS_0, 
  SOH.HLDCOD_0, 
  SOQ.QTY_0, 
  SOQ.DLVQTY_0, 
  SOQ.OPRQTY_0, 
  SOQ.ALLQTY_0, 
  ITM2.ITMREF_0, 
  ITM2.ITMDES1_0, 
  ITM2.ITMDES2_0, 
  SOH.BETFCY_0, 
  ITM2.ITMDES3_0, 
  SOH.SHIDAT_0,
  SOQ.STOFCY_0,
  STK.DC30,
  STK.DC33,
  STK.[1600],
  STK.[2100],
  STK.[2200],
  STK.[2300],
  STK.[2600],
  SUM_STOCK,
  PO.EARLIEST_PO,
  PO.ETA,
  PO.PO_VENDOR,
  ITP.PRIO_VENDOR,
  ITP.MOQ,
  SALES.DC30_SALES_1M,
  SALES.DC30_SALES_3M,
  SALES.DC30_SALES_12M,
  SALES.DC33_SALES_1M,
  SALES.DC33_SALES_3M,
  SALES.DC33_SALES_12M,
  SALES.ALL_SALES_1M,
  SALES.ALL_SALES_3M,
  SALES.ALL_SALES_12M,
  SALES.RETAIL_SALES_1M,
  SALES.RETAIL_SALES_3M,
  SALES.RETAIL_SALES_12M