WITH VendorInfo AS (
    SELECT
        ITMREF_0,
        ITP.BPSNUM_0,
        ITP.BPSNUM_0 + ' ' + BPS.BPSNAM_0 AS VendorName,
        ROW_NUMBER() OVER (PARTITION BY ITMREF_0 ORDER BY CASE WHEN PIO_0 = 0 THEN 0 ELSE 1 END, PIO_0) AS VendorRank
    FROM LIVE.ITMBPS ITP
    LEFT JOIN LIVE.BPSUPPLIER BPS ON BPS.BPSNUM_0 = ITP.BPSNUM_0
),
SalesData AS (
    SELECT
        SID.ITMREF_0,
        SID.CREDAT_0 AS SalesDate,
        SUM(CASE WHEN SIV.SALFCY_0 = 'DC30' THEN SID.AMTNOTLIN_0*SIH.SNS_0 ELSE 0 END) AS SalesDC30,
        SUM(CASE WHEN SIV.SALFCY_0 = 'DC31' THEN SID.AMTNOTLIN_0*SIH.SNS_0 ELSE 0 END) AS SalesDC31,
        SUM(CASE WHEN SIV.SALFCY_0 = 'DC33' THEN SID.AMTNOTLIN_0*SIH.SNS_0 ELSE 0 END) AS SalesDC33,
        SUM(CASE WHEN SIV.SALFCY_0 = 'DC52' THEN SID.AMTNOTLIN_0*SIH.SNS_0 ELSE 0 END) AS SalesDC52,
        SUM(CASE WHEN SIV.SALFCY_0 = '1200' THEN SID.AMTNOTLIN_0*SIH.SNS_0 ELSE 0 END) AS SalesDuncan,
        SUM(CASE WHEN SIV.SALFCY_0 = '1600' THEN SID.AMTNOTLIN_0*SIH.SNS_0 ELSE 0 END) AS SalesCourt,
        SUM(CASE WHEN SIV.SALFCY_0 = '1800' THEN SID.AMTNOTLIN_0*SIH.SNS_0 ELSE 0 END) AS SalesPH,
        SUM(CASE WHEN SIV.SALFCY_0 = '2100' THEN SID.AMTNOTLIN_0*SIH.SNS_0 ELSE 0 END) AS SalesFort,
        SUM(CASE WHEN SIV.SALFCY_0 = '2200' THEN SID.AMTNOTLIN_0*SIH.SNS_0 ELSE 0 END) AS SalesOak,
        SUM(CASE WHEN SIV.SALFCY_0 = '2300' THEN SID.AMTNOTLIN_0*SIH.SNS_0 ELSE 0 END) AS SalesBroad,
        SUM(CASE WHEN SIV.SALFCY_0 = '2400' THEN SID.AMTNOTLIN_0*SIH.SNS_0 ELSE 0 END) AS SalesRylOak,
        SUM(CASE WHEN SIV.SALFCY_0 = '2500' THEN SID.AMTNOTLIN_0*SIH.SNS_0 ELSE 0 END) AS SalesTusc,
        SUM(CASE WHEN SIV.SALFCY_0 = '2600' THEN SID.AMTNOTLIN_0*SIH.SNS_0 ELSE 0 END) AS SalesSidney,
        SUM(CASE WHEN SIV.SALFCY_0 = '2700' THEN SID.AMTNOTLIN_0*SIH.SNS_0 ELSE 0 END) AS SalesFortIB,
        SUM(CASE WHEN SIV.SALFCY_0 = '2800' THEN SID.AMTNOTLIN_0*SIH.SNS_0 ELSE 0 END) AS SalesSidneyIB,
        SUM(CASE WHEN SIV.SALFCY_0 = '3200' THEN SID.AMTNOTLIN_0*SIH.SNS_0 ELSE 0 END) AS Sales3200,
        SUM(SID.AMTNOTLIN_0*SIH.SNS_0) AS TotalSales
    FROM LIVE.SINVOICED SID
    INNER JOIN LIVE.SINVOICEV SIV ON SID.NUM_0 = SIV.NUM_0
    INNER JOIN LIVE.SINVOICE SIH ON SIV.NUM_0=SIH.NUM_0
    GROUP BY SID.ITMREF_0, SID.CREDAT_0
),
StockData AS (
    SELECT
        STO.ITMREF_0,
        SUM(CASE WHEN STO.STOFCY_0 = 'DC30' THEN STO.QTYSTU_0 ELSE 0 END) AS StockTotalDC30,
        SUM(CASE WHEN STO.STOFCY_0 = '1600' THEN STO.QTYSTU_0 ELSE 0 END) AS StockTotalCourt,
        SUM(CASE WHEN STO.STOFCY_0 = '2100' THEN STO.QTYSTU_0 ELSE 0 END) AS StockTotalFort,
        SUM(CASE WHEN STO.STOFCY_0 = '2200' THEN STO.QTYSTU_0 ELSE 0 END) AS StockTotalOak,
        SUM(CASE WHEN STO.STOFCY_0 = '2300' THEN STO.QTYSTU_0 ELSE 0 END) AS StockTotalBroad,
        SUM(CASE WHEN STO.STOFCY_0 = '2600' THEN STO.QTYSTU_0 ELSE 0 END) AS StockTotalSidney,
        SUM(CASE WHEN STO.STOFCY_0 = '3200' THEN STO.QTYSTU_0 ELSE 0 END) AS StockTotal3200
    FROM LIVE.STOCK STO
    GROUP BY STO.ITMREF_0
),
SpriceListAggregate AS (
    SELECT
        PLICRI2_0,
        PRI_0,
        ROW_NUMBER() OVER (PARTITION BY PLICRI2_0 ORDER BY MAXQTY_0 ASC) AS rn
    FROM LIVE.SPRICLIST
    WHERE PLI_0 = '11' AND PLICRI1_0 = 'PL2'
)
SELECT
    ITM.ITMREF_0 AS ProductCode,
    ITM.ITMDES1_0 AS ProductDescription,
    ISNULL(ITM.TSICOD_0,'N/A') AS MonkStatus,
    ISNULL(ATX.TEXTE_0,'0 - NO CLASS') AS MonkClass,
    ITM.STU_0 AS StockUnit,
    ISNULL(ITF.SAFSTO_0, 0) AS DC30SafetyStock,
    ISNULL(ITF.REOMINQTY_0, 0) AS ProductEOQ,
    SD.SalesDate,
    ISNULL(SD.SalesDC30,0),
    ISNULL(SD.SalesDC31,0),
    ISNULL(SD.SalesDC33,0),
    ISNULL(SD.SalesDC52,0),
    ISNULL(SD.SalesDuncan,0),
    ISNULL(SD.SalesCourt,0),
    ISNULL(SD.SalesPH,0),
    ISNULL(SD.SalesFort,0),
    ISNULL(SD.SalesOak,0),
    ISNULL(SD.SalesBroad,0),
    ISNULL(SD.SalesRylOak,0),
    ISNULL(SD.SalesTusc,0),
    ISNULL(SD.SalesSidney,0),
    ISNULL(SD.SalesFortIB,0),
    ISNULL(SD.SalesSidneyIB,0),
    ISNULL(SD.Sales3200,0),
    ISNULL(SD.TotalSales,0),
    ISNULL(STD.StockTotalDC30,0),
    ISNULL(STD.StockTotalCourt,0),
    ISNULL(STD.StockTotalFort,0),
    ISNULL(STD.StockTotalOak,0),
    ISNULL(STD.StockTotalBroad,0),
    ISNULL(STD.StockTotalSidney,0),
    ISNULL(STD.StockTotal3200,0),
    ITM.RPLITM_0 AS AlternateProduct,
    MAX(CASE WHEN VI.VendorRank = 1 THEN VI.VendorName ELSE 'N/A' END) AS PrimaryVendor,
    MAX(CASE WHEN VI.VendorRank = 2 THEN VI.VendorName ELSE 'N/A' END) AS SecondaryVendor,
    MAX(CASE WHEN VI.VendorRank = 1 THEN PP.PRI_0 ELSE 0 END) AS PrimarySupplierCost,
    MAX(CASE WHEN VI.VendorRank = 2 THEN PP.PRI_0 ELSE 0 END) AS SecondSupplierCost,
    ISNULL(SLA.PRI_0, 0) AS CustPL2Price
FROM LIVE.ITMMASTER ITM
LEFT JOIN LIVE.ATEXTRA ATX ON ATX.CODFIC_0 = 'ATABDIV'
    AND ATX.IDENT1_0 = '21'
    AND ATX.ZONE_0 = 'LNGDES'
    AND ATX.LANGUE_0 = 'ENG'
    AND ATX.IDENT2_0 = ITM.TSICOD_1
LEFT JOIN LIVE.ITMFACILIT ITF ON ITM.ITMREF_0 = ITF.ITMREF_0 AND ITF.STOFCY_0 = 'DC30'
LEFT JOIN SalesData SD ON ITM.ITMREF_0 = SD.ITMREF_0
LEFT JOIN StockData STD ON ITM.ITMREF_0 = STD.ITMREF_0
LEFT JOIN VendorInfo VI ON ITM.ITMREF_0 = VI.ITMREF_0
LEFT JOIN LIVE.PPRICLIST PP ON ITM.ITMREF_0 = PP.PLICRI2_0 AND PP.PLICRI1_0 = VI.BPSNUM_0 AND PP.PLI_0 = 'T20'
LEFT JOIN SpriceListAggregate SLA ON ITM.ITMREF_0 = SLA.PLICRI2_0 AND SLA.rn = 1
GROUP BY
    ITM.ITMREF_0,
    ITM.ITMDES1_0,
    ITM.TSICOD_0,
    ATX.TEXTE_0,
    ITM.STU_0,
    ITF.SAFSTO_0,
    ITF.REOMINQTY_0,
    SD.SalesDate,
    SD.SalesDC30,
    SD.SalesDC31,
    SD.SalesDC33,
    SD.SalesDC52,
    SD.SalesDuncan,
    SD.SalesCourt,
    SD.SalesPH,
    SD.SalesFort,
    SD.SalesOak,
    SD.SalesBroad,
    SD.SalesRylOak,
    SD.SalesTusc,
    SD.SalesSidney,
    SD.SalesFortIB,
    SD.SalesSidneyIB,
    SD.Sales3200,
    SD.TotalSales,
    STD.StockTotalDC30,
    STD.StockTotalCourt,
    STD.StockTotalFort,
    STD.StockTotalOak,
    STD.StockTotalBroad,
    STD.StockTotalSidney,
    STD.StockTotal3200,
    ITM.RPLITM_0,
    SLA.PRI_0