SELECT
SOQ.CREDAT_0,
SOQ.ITMREF_0,
SOQ.QTY_0-SOQ.DLVQTY_0,
SOQ.SOHNUM_0,
SOH.CUSORDREF_0,
SOQ.SOQSTA_0

FROM LIVE.SORDERQ SOQ
LEFT OUTER JOIN LIVE.SORDER SOH ON SOQ.SOHNUM_0 = SOH.SOHNUM_0

WHERE SOH.CUSORDREF_0 LIKE '%'+%1%+'%' AND SOQ.CREDAT_0 >= DATEADD(DAY, -365, GETDATE())
AND (SELECT CCE_1 FROM LIVE.ITMMASTER WHERE ITMREF_0 = SOQ.ITMREF_0) = 'TCR'
order by SOQ.CREDAT_0 desc