SELECT
	SIV.REP_0,
	REP.REPNAM_0, 
	CONVERT(VARCHAR, CAST(SUM(SIH.AMTNOT_0) AS DECIMAL(18,2)))
FROM LIVE.SINVOICEV SIV
	LEFT OUTER JOIN LIVE.SALESREP REP ON SIV.REP_0 = REP.REPNUM_0
	LEFT OUTER JOIN LIVE.SINVOICE SIH ON SIV.NUM_0 = SIH.NUM_0
WHERE 
SIH.STA_0 = 3
AND ACCDAT_0 >= CASE
	WHEN MONTH(GETDATE()) BETWEEN 1 AND 6 THEN CONVERT(VARCHAR, YEAR(GETDATE())-1)+'0701'
	ELSE CONVERT(VARCHAR, YEAR(GETDATE()))+'0701'
END
AND ACCDAT_0 <= CASE
	WHEN MONTH(GETDATE()) BETWEEN 1 AND 6 THEN CONVERT(VARCHAR, YEAR(GETDATE()))+'0630'
	ELSE CONVERT(VARCHAR, YEAR(GETDATE())+1)+'0630'
END
GROUP BY SIV.REP_0, REP.REPNAM_0