SELECT
SOH.SOHNUM_0,
CASE
WHEN SOQ.FMINUM_0 <> '' THEN SOQ.FMINUM_0
ELSE 'NO PO'
END,
SOH.BPCORD_0,
BPC.BPCNAM_0,
SOQ.ITMREF_0,
ITM.ITMDES1_0+' '+ITM.ITMDES2_0,
CAST(SOQ.QTY_0-SOQ.DLVQTY_0-SOQ.ALLQTY_0-SOQ.PREQTY_0 AS INT),
CONVERT(VARCHAR,POQ.EXTRCPDAT_0,101)

FROM LIVE.SORDER SOH
LEFT OUTER JOIN LIVE.SORDERQ SOQ ON SOH.SOHNUM_0 = SOQ.SOHNUM_0
LEFT OUTER JOIN LIVE.ITMMASTER ITM ON SOQ.ITMREF_0 = ITM.ITMREF_0
LEFT OUTER JOIN LIVE.PORDERQ POQ ON SOQ.ITMREF_0 = POQ.ITMREF_0 AND SOQ.FMINUM_0 = POQ.POHNUM_0
LEFT OUTER JOIN LIVE.SORDERP SOP ON SOQ.ITMREF_0 = SOP.ITMREF_0 AND SOQ.SOQSEQ_0 = SOP.SOPSEQ_0 AND SOQ.SOHNUM_0 = SOP.SOHNUM_0 AND SOQ.SOPLIN_0 = SOP.SOPLIN_0
LEFT OUTER JOIN LIVE.BPCUSTOMER BPC ON SOH.BPCORD_0 = BPC.BPCNUM_0

WHERE (POQ.LINCLEFLG_0 = 1 OR SOQ.FMINUM_0 = '') AND SOH.ORDSTA_0 = 1 AND SOQ.SOQSTA_0 <> 3 AND SOQ.ITMREF_0 NOT LIKE '/%' AND (SOH.STOFCY_0 = 'DC31' OR (SOH.STOFCY_0 = 'DC30' AND ITM.CCE_1 IN ('FURN','FURNSERVC') AND CONVERT(VARCHAR,SOH.YINSTALLDATE_0,101) = '' AND SOH.DRN_0 IN (19,20,21,36,30)))