SELECT
  ITM.SEAKEY_0 AS [Basics Number],
  ITM.ITMREF_0,
  (
    SELECT TOP 1
      BPSNUM_0
    FROM LIVE.ITMBPS ITP
    WHERE ITP.ITMREF_0 = ITM.ITMREF_0
      AND (SELECT BPRPAY_0 FROM LIVE.BPSUPPLIER BPS WHERE BPS.BPSNUM_0 = ITP.BPSNUM_0) = 'V5555'
    ORDER BY PIO_0 ASC
  ) AS [Priority 0 Supplier Number],
  (
    SELECT TOP 1
      ITMREFBPS_0
    FROM LIVE.ITMBPS ITP
    WHERE ITP.ITMREF_0 = ITM.ITMREF_0
      AND (SELECT BPRPAY_0 FROM LIVE.BPSUPPLIER BPS WHERE BPS.BPSNUM_0 = ITP.BPSNUM_0) = 'V5555'
    ORDER BY PIO_0 ASC
  ) AS [Priority 0 Supplier Code],
  ITM.STU_0 AS [Unit of Measure]
FROM LIVE.ITMMASTER ITM
WHERE ITM.SEAKEY_0 <> ''
  AND EXISTS (
    SELECT 1
    FROM LIVE.ITMBPS ITP
    WHERE ITP.ITMREF_0 = ITM.ITMREF_0
      AND (SELECT BPRPAY_0 FROM LIVE.BPSUPPLIER BPS WHERE BPS.BPSNUM_0 = ITP.BPSNUM_0) = 'V5555'
  )
  AND (
    SELECT TOP 1
      BPSNUM_0
    FROM LIVE.ITMBPS ITP
    WHERE ITP.ITMREF_0 = ITM.ITMREF_0
      AND (SELECT BPRPAY_0 FROM LIVE.BPSUPPLIER BPS WHERE BPS.BPSNUM_0 = ITP.BPSNUM_0) = 'V5555'
    AND PIO_0=0
  ) IS NOT NULL