SELECT
HAE.NUM_0,
HAE.TYP_0,
PYD.VCRNUM_0,
SDH.SOHNUM_0

FROM LIVE.GACCENTRY HAE
LEFT OUTER JOIN LIVE.PAYMENTD PYD ON 
CASE
WHEN LEN(REFINT_0)>4 AND HAE.NUM_0 LIKE 'DEPOS%' THEN RIGHT(HAE.REFINT_0, LEN(HAE.REFINT_0)-4)
ELSE HAE.BPRVCR_0
END = PYD.NUM_0
LEFT OUTER JOIN LIVE.SINVOICEV SIV ON PYD.VCRNUM_0 = SIV.NUM_0
LEFT OUTER JOIN LIVE.SDELIVERY SDH ON SIV.SIHORINUM_0 = SDH.SDHNUM_0