SELECT
ITM.ITMREF_0,
ITM.ITMDES1_0,
ITM.TSICOD_0,
ITM.ACCCOD_0,
APL.LANMES_0,
ITM.TCLCOD_0,
ITM.STU_0,
ITM.CREDAT_0,
ITM.YDISDAT_0,
ITM.UPDDAT_0,
FORMAT(CAST(ITM.UPDDATTIM_0 AT TIME ZONE 'UTC' AS DATETIMEOFFSET) AT TIME ZONE 'Pacific Standard Time', 'HHmmss'),
ITM.UPDUSR_0

FROM LIVE.ITMMASTER ITM
LEFT JOIN LIVE.APLSTD APL ON ITM.ITMSTA_0 = LANNUM_0
        AND LANCHP_0 = '246'
        AND LAN_0 = 'ENG'