SELECT DISTINCT
STO.STOFCY_0,
STO.ITMREF_0,
ITM.ITMDES1_0+' '+ITM.ITMDES2_0,
STO.LOCTYP_0,
STO.LOC_0,
SUM(cast(STO.QTYSTU_0 as int)),
SUM(cast(STO.CUMALLQTY_0 as int))

FROM LIVE.STOCK STO
LEFT OUTER JOIN LIVE.ITMMASTER ITM ON STO.ITMREF_0 = ITM.ITMREF_0
WHERE STO.STOFCY_0 in ('DC30','DC33') and ITM.ACCCOD_0 IN ('STATIONERY','ART') AND
(
Select distinct
count(distinct STO2.LOC_0)
from LIVE.STOCK STO2
WHERE STO2.ITMREF_0 = STO.ITMREF_0 and STO2.STOFCY_0 = STO.STOFCY_0 AND STO2.STA_0 = 'A'
) > 1
AND ITM.TSICOD_0 NOT IN ('MT')
AND
(
SELECT TOP 1
ITP.BPSNUM_0
FROM LIVE.ITMBPS ITP
WHERE ITP.PIO_0 = 0 AND ITP.ITMREF_0 = STO.ITMREF_0
) <> 'V5664'
AND STO.STA_0 = 'A'


group by 
STO.STOFCY_0,
STO.ITMREF_0,
ITM.ITMDES1_0+' '+ITM.ITMDES2_0,
STO.LOCTYP_0,
STO.LOC_0