With LocData AS (
	SELECT
		STO.STOFCY_0,
		STO.ITMREF_0,
		STO.LOC_0,
		SUM(CASE WHEN STA_0='A' THEN QTYSTU_0-CUMALLQTY_0 ELSE 0 END) AS STA_A,
		SUM(CASE WHEN STA_0='Q' THEN QTYSTU_0 ELSE 0 END) AS STA_Q,
		SUM(CASE WHEN STA_0='R' THEN QTYSTU_0 ELSE 0 END) AS STA_R
	FROM LIVE.STOCK STO
	Group by STOFCY_0,ITMREF_0,LOC_0,QTYSTU_0,CUMALLQTY_0
)

SELECT
LOC.STOFCY_0,
ITM.ITMREF_0,
LOC.LOC_0,
SUM(LOC.STA_A),
SUM(LOC.STA_Q),
SUM(LOC.STA_R)

FROM LIVE.ITMMASTER ITM
LEFT JOIN LocData LOC ON ITM.ITMREF_0=LOC.ITMREF_0
GROUP BY LOC.STOFCY_0,ITM.ITMREF_0,LOC.LOC_0