WITH LatestSupplierReceipt AS (
  SELECT 
    STJ1.CREDAT_0,
    STJ1.STOFCY_0,
    STJ1.ITMREF_0,
    STJ1.PRIORD_0
  FROM LIVE.STOJOU STJ1
  WHERE 
    STJ1.TRSTYP_0 = 3 
    AND STJ1.STOFCY_0 = 'DC30'
    AND STJ1.REGFLG_0 = 1
),
STOJOUWithLatestSupplierPrice AS (
  SELECT 
    STJ.*,
    (
      SELECT TOP 1 LSR.PRIORD_0
      FROM LatestSupplierReceipt LSR
      WHERE 
        LSR.ITMREF_0 = STJ.ITMREF_0
        AND LSR.CREDAT_0 <= STJ.CREDAT_0
      ORDER BY LSR.CREDAT_0 DESC
    ) AS LatestSupplierPrice
  FROM LIVE.STOJOU STJ
  WHERE 
    STJ.TRSTYP_0 IN (1, 2, 3, 4, 12, 13)
    AND STJ.REGFLG_0 = 1
)

SELECT 
  ITM.ACCCOD_0, 
  STJ.CREDAT_0, 
  ITF.STOFCY_0, 
  ITM.ITMREF_0, 
  ITM.ITMDES1_0, 
  STJ.STU_0, 
  CASE WHEN (STJ.TRSTYP_0 = 1) THEN STJ.QTYSTU_0 ELSE 0 END AS MiscReceipt, 
  CASE WHEN (STJ.TRSTYP_0 = 1) THEN STJ.PRIORD_0 * STJ.QTYSTU_0 ELSE 0 END AS MiscReceiptVal, 

  CASE WHEN (STJ.TRSTYP_0 = 2) THEN STJ.QTYSTU_0 ELSE 0 END AS MiscIssue, 
  CASE WHEN (STJ.TRSTYP_0 = 2) THEN STJ.PRIORD_0 * STJ.QTYSTU_0 ELSE 0 END AS MiscIssueVal, 

  CASE WHEN (STJ.TRSTYP_0 = 3) THEN STJ.QTYSTU_0 ELSE 0 END AS SupplierReceipt, 
  CASE WHEN (STJ.TRSTYP_0 = 3) THEN STJ.PRIORD_0 * STJ.QTYSTU_0 ELSE 0 END AS SupplierReceiptVal, 

  CASE WHEN (STJ.TRSTYP_0 = 4) THEN STJ.QTYSTU_0 ELSE 0 END AS CustomerDelivery, 
  ISNULL(
    CASE WHEN (STJ.TRSTYP_0 = 4 AND STJ.AMTVAL_0 <> 0) THEN STJ.LatestSupplierPrice * STJ.QTYSTU_0 ELSE 0 END, 
    IVT.AVC_0*STJ.QTYSTU_0
  ) AS CustomerDeliveryVal, 

  CASE WHEN (STJ.TRSTYP_0 = 12) THEN STJ.QTYSTU_0 ELSE 0 END AS DeliveryReturn, 
  ISNULL(
    CASE WHEN (STJ.TRSTYP_0 = 12 AND STJ.AMTVAL_0 <> 0) THEN STJ.LatestSupplierPrice * STJ.QTYSTU_0 ELSE 0 END, 
    IVT.AVC_0*STJ.QTYSTU_0
  ) AS DeliveryReturnVal, 

  CASE WHEN (STJ.TRSTYP_0 = 13) THEN STJ.QTYSTU_0 ELSE 0 END AS CountQty, 
  CASE WHEN (STJ.TRSTYP_0 = 13) THEN STJ.AMTVAL_0 ELSE 0 END AS CountVal, 

  CASE WHEN (STJ.TRSTYP_0 IN (1, 2, 3, 4, 12, 13)) THEN STJ.QTYSTU_0 ELSE 0 END AS TotalQty, 

  (
    CASE WHEN (STJ.TRSTYP_0 IN (1, 2, 3, 13)) THEN STJ.PRIORD_0 * STJ.QTYSTU_0 ELSE 0 END
  ) + ISNULL(
    CASE WHEN STJ.TRSTYP_0 IN (4, 12) AND STJ.AMTVAL_0 <> 0 THEN STJ.LatestSupplierPrice * STJ.QTYSTU_0 ELSE 0 END, 
   IVT.AVC_0*STJ.QTYSTU_0
  ) AS TotalVal 

FROM 
  LIVE.ITMFACILIT ITF
  INNER JOIN LIVE.ITMMASTER ITM ON ITF.ITMREF_0 = ITM.ITMREF_0
  LEFT JOIN STOJOUWithLatestSupplierPrice STJ ON ITF.ITMREF_0 = STJ.ITMREF_0 
  AND ITF.STOFCY_0 = STJ.STOFCY_0
  LEFT JOIN LIVE.ITMMVT IVT ON ITF.ITMREF_0=IVT.ITMREF_0 AND ITF.STOFCY_0=IVT.STOFCY_0
