With ReceivedQuantities As (
	SELECT
		SDHNUM_0,
		SDDLIN_0,
		ITMREF_0,
		SUM(QTYUOM_0) AS ReceivedTotal
	FROM
		LIVE.PRECEIPTD
	GROUP BY
		SDHNUM_0,
		SDDLIN_0,
		ITMREF_0
)

SELECT
CONVERT(VARCHAR(10), ZRD.UPDDATTIM_0, 120) as [Date],
ZRD.RECFCY_0 as [Site],
ZRD.SDHNUM_0 as [Delivery],
ZRD.ITMREF_0 as [Product],
ITMDES1_0 as [Description],
QTYDLV_0 as [Expected],
QTYRCP_0 as [Received],
LINSTA_0 as [Status]
FROM LIVE.ZINTRD ZRD
LEFT JOIN LIVE.ZINTRH ZRH ON ZRD.ZRHNUM_0=ZRH.ZRHNUM_0 
LEFT JOIN ReceivedQuantities RCQ ON ZRD.SDHNUM_0=RCQ.SDHNUM_0 and ZRD.SDDLIN_0=RCQ.SDDLIN_0 and ZRD.ITMREF_0=RCQ.ITMREF_0
WHERE ZRH.ZRHSTA_0=2 AND ((ZRD.ZRHSTA_0=2 and LINSTA_0='SHORT' and isnull(RCQ.ReceivedTotal,0)=ZRD.QTYRCP_0) OR LINSTA_0 in ('KEEP','RETURN'))