 ( NUM_0 , LIN_0 , ACC_0 , CHK_0 , CHKDAT_0 , ACCNUM_0 , USER_0 , UPDDATTIM_0 
 ) As 
SELECT        NUM_0, LIN_0 ,ACC_0, CHK_0, CHKDAT_0, D.ACCNUM_0, D.UPDUSR_0, D.UPDDATTIM_0
FROM            x3.LIVE.GACCENTRYD D LEFT OUTER JOIN
                         x3.LIVE.BANRECD B ON D.ACCNUM_0 = B.ACCNUM_0
where B.ACCNUM_0 is NULL and left(D.ACC_0,1)='1' and CHK_0<>''
