 ( SIHORI_0 , NUM_0 , SIHNUMORI_0 , SIHNUM_0 ) As 
select SIV.SIHORI_0, SIV.NUM_0, SIV.SIHORINUM_0, SID.NUM_0 as OrigInv from 
    SINVOICEV SIV INNER JOIN SRETURND SRD on SIV.SIHORINUM_0 = SRD.SRHNUM_0
	                       INNER JOIN SINVOICED SID ON SRD.SDHNUM_0 = SID.SDHNUM_0 and SRD.SDDLIN_0 = SID.SDDLIN_0
WHERE SIV.SIHORI_0 = 6 and SRD.SDHNUM_0 <> ''
group by SIV.SIHORI_0, SIV.NUM_0, SIV.SIHORINUM_0, SID.NUM_0 having count(*) = 1
union
select SIV.SIHORI_0, SIV.NUM_0, SIV.SIHORINUM_0, SIV.SIHORINUM_0 as OrigInv
from SINVOICEV SIV 
where SIV.SIHORI_0 = 4
