 ( DES_0_0 , MINDAT_0_0 , MAXDAT_0_0 , DLVNUM_0 , DLVLIN_0 , AMT_0 , MIN_NUM_0 
 , MIN_LIN_0 , MINLIN_1_0 , MIN_ACCNUM_0 , MAX_NUM_0 , MAX_LIN_0 , MAXLIN_1_0 
 , MAX_ACCNUM_0 ) As 
SELECT        DES_0, MIN(ACCDAT_0) AS MINDAT_0, MAX(ACCDAT_0) AS MAXDAT_0, CAST(CASE WHEN CHARINDEX('/', DES_0) < 1 THEN DES_0 ELSE (LEFT(DES_0, CHARINDEX('/', DES_0) - 1)) END AS CHAR) AS DLVNUM, CAST(CASE WHEN LEN(DES_0) 
                         < 14 THEN DES_0 ELSE (CASE WHEN LEFT(RIGHT(LIVE.GACCENTRYD.DES_0, 5), 1) = '/' THEN RIGHT(LIVE.GACCENTRYD.DES_0, 4) ELSE (CASE WHEN LEFT(RIGHT(LIVE.GACCENTRYD.DES_0, 5), 1) 
                         <> '/' THEN RIGHT(LIVE.GACCENTRYD.DES_0, 5) ELSE '' END) END) END AS INT) AS DLVLIN, SUM(AMTLED_0 * SNS_0) AS AMT, MIN(NUM_0) AS MIN_NUM, MIN(LIN_0) * 1000 AS MIN_LIN, MIN(LIN_0) AS MINLIN_1, 
                         MIN(ACCNUM_0) AS MIN_ACCNUM, MAX(NUM_0) AS MAX_NUM, MAX(LIN_0) * 1000 AS MAX_LIN, MAX(LIN_0) AS MAXLIN_1, MAX(ACCNUM_0) AS MAX_ACCNUM
FROM            LIVE.GACCENTRYD
WHERE        (ACC_0 = '41900')
GROUP BY DES_0
