With SalesOrderLine as (
	SELECT
		SOQ.SOHNUM_0,
		SOQ.SOPLIN_0,
		SOQ.ITMREF_0,
		SOQ.QTY_0,
		SOQ.DLVQTY_0,
		SOQ.LPRQTY_0,
		SOQ.OPRQTY_0,
		SOP.SAU_0,
		SOP.SAUSTUCOE_0,
		SOP.GROPRI_0,
		SOP.CPRPRI_0,
		SOP.VACITM_0,
		SOP.VACITM_1,
		SOP.VACITM_2,
		SOP.CLCAMT1_0
	FROM
		LIVE.SORDERQ SOQ
	LEFT OUTER JOIN LIVE.SORDERP SOP ON SOQ.ITMREF_0=SOP.ITMREF_0 and SOQ.SOPLIN_0=SOP.SOPLIN_0 and SOQ.SOQSEQ_0=SOP.SOPSEQ_0 and SOQ.SOHNUM_0=SOP.SOHNUM_0
),
Allocations as (
	SELECT
		VCRNUM_0,
		VCRLIN_0,
		ITMREF_0,
		QTYSTU_0
	FROM LIVE.STOALL
		WHERE QTYSTU_0>0
),
ProductDetails as (
    SELECT
        ITM.ITMREF_0,
        ITM.ITMDES1_0,
        ITM.ITMDES2_0,
        ITM.ITMDES3_0,
        ITM.TSICOD_0,
		ITM.SEAKEY_0
    FROM LIVE.ITMMASTER ITM
)
Select
SOH.SOHNUM_0 as [Sales Order],
LIN.SOPLIN_0 as [Sales Order Line],
LIN.ITMREF_0 as [Product],
PRO.ITMDES1_0 as [Description 1],
PRO.ITMDES2_0 as [Description 2],
PRO.ITMDES3_0 as [Description 3],
PRO.TSICOD_0 as [Status],
PRO.SEAKEY_0 as [Catalogue #],
LIN.QTY_0 as [Ordered Quantity],
LIN.DLVQTY_0 as [Delivered],
LIN.LPRQTY_0 as [Being Prepared],
LIN.OPRQTY_0 as [Prepared],
isnull(ALO.QTYSTU_0*LIN.SAUSTUCOE_0,0) as [Allocated],
abs(LIN.QTY_0-(LIN.DLVQTY_0+LIN.LPRQTY_0+LIN.OPRQTY_0+isnull(ALO.QTYSTU_0*LIN.SAUSTUCOE_0,0))) as [Backordered],
LIN.QTY_0-LIN.DLVQTY_0 as [Remaining to Deliver],
LIN.SAU_0 as [Sales Unit],
LIN.GROPRI_0 as [Gross Price],
LIN.CPRPRI_0 as [Cost Price],
LIN.VACITM_0 as [Tax 1],
LIN.VACITM_1 as [Tax 2],
LIN.VACITM_2 as [Tax 3],
LIN.CLCAMT1_0/LIN.QTY_0 as [EHF Basis],
LIN.QTY_0*(LIN.CLCAMT1_0/LIN.QTY_0) as [EHF Total],
LIN.QTY_0*LIN.GROPRI_0 as [Gross Total],
CASE
	WHEN LIN.VACITM_0='GST' then ROUND(LIN.QTY_0*LIN.GROPRI_0*0.05,2)
	ELSE 0
END as [GST Total],
CASE
	WHEN LIN.VACITM_1='PST' then ROUND(LIN.QTY_0*LIN.GROPRI_0*0.07,2)
	ELSE 0
END as [PST Total]

From LIVE.SORDER SOH
Left Join SalesOrderLine LIN ON SOH.SOHNUM_0=LIN.SOHNUM_0
Left join Allocations ALO on LIN.ITMREF_0=ALO.ITMREF_0 and LIN.SOHNUM_0=ALO.VCRNUM_0 and LIN.SOPLIN_0=ALO.VCRLIN_0
Left Join ProductDetails PRO on LIN.ITMREF_0=PRO.ITMREF_0
WHERE LIN.SOHNUM_0='WEB153830'