 ( VCRNUM_0 , DTAVAT_0 , DTAAMT_0 ) As 

SELECT VCRNUM_0, DTAVAT_0, DTAAMT_0  
 FROM  LIVE.SVCRFOOT "SVCRFOOT" 
 LEFT OUTER JOIN SFOOTINV  "SFOOTINV" ON "SVCRFOOT"."DTA_0"="SFOOTINV"."SFINUM_0"
  WHERE  
   SFINUMCAR_0 = 9
