 ( DTAVAT_0 , VAT_0 , VATRAT_0 , DTAAMT_0 , TOTAL_0 , BASTAX_0 , AMTTAX_0 
 , VCRNUM_0 , VCRTYP_0 ) As 
 SELECT DTAVAT_0, "SVCRVAT".VAT_0,  "SVCRVAT"."VATRAT_0",  "SVCRFOOT"."DTAAMT_0", ("SVCRFOOT"."DTAAMT_0" * "SVCRVAT"."VATRAT_0") /100 total, "SVCRVAT"."BASTAX_0", "SVCRVAT"."AMTTAX_0", "SVCRFOOT"."VCRNUM_0", "SVCRVAT"."VCRTYP_0"
 FROM  SVCRFOOT "SVCRFOOT" 
 LEFT OUTER JOIN SFOOTINV  "SFOOTINV" ON "SVCRFOOT"."DTA_0"="SFOOTINV"."SFINUM_0"
 LEFT OUTER JOIN SVCRVAT  "SVCRVAT" ON  "SVCRVAT".VCRNUM_0 = "SVCRFOOT"."VCRNUM_0" 
 INNER JOIN TABVAT  "TABVAT" ON "SVCRVAT"."VAT_0"="TABVAT"."VAT_0" 
 WHERE  
   SFINUMCAR_0 = 9
  AND "SVCRVAT"."VAT_0"="TABVAT"."VAT_0" AND ("TABVAT"."LEG_0"=N'USA' OR "TABVAT"."LEG_0"=N' ') 
  AND "SVCRVAT".VAT_0 NOT IN ('NT','NTA','EHF') 
  
