 ( USRDAT_0 , SITE_0 , PRHNUM_0 , PRLNUM_0 , SDHNUM_0 , SOHNUM_0 , NEXTSTEP_0 
 , BPCNAM_0 , REP_0 , NUMLIN_0 ) As 
Select CREDAT_0, STOFCY_0, '', '', SDHNUM_0, SOHNUM_0, '0.Validate intersite',BPCORD_0+','+BPDNAM_0, REP_0,0 FROM SDELIVERY where BETFCY_0=2 AND CFMFLG_0=1
Union
SELECT CREDAT_0, STOFCY_0, '', PRLNUM_0, '', 'more than 1', '1.Create pick', 'more than 1','',0 FROM STOPRELIS WHERE PRHNUM_0=''
union
select CREDAT_0, STOFCY_0, PRHNUM_0, PRLNUM_0, SDHNUM_0, isnull((SELECT top 1 ORINUM_0 FROM STOPRELIS WHERE STOPRELIS.PRHNUM_0=STOPREH.PRHNUM_0),'') ,'2.Invoice' as [Next Step], ISNULL((SELECT BPCORD_0+','+BPDNAM_0 from SDELIVERY WHERE SDELIVERY.SDHNUM_0=STOPREH.SDHNUM_0),''), ISNULL((SELECT REP_0 from SDELIVERY WHERE SDELIVERY.SDHNUM_0=STOPREH.SDHNUM_0),''),0 from STOPREH where SDHNUM_0<>'' AND SDHTYP_0='SDH' GROUP BY CREDAT_0, STOFCY_0, PRHNUM_0, PRLNUM_0, SDHNUM_0 HAVING ISNULL((SELECT INVFLG_0 from SDELIVERY WHERE SDELIVERY.SDHNUM_0=STOPREH.SDHNUM_0),1)=1 and ISNULL((SELECT BETFCY_0 from SDELIVERY WHERE SDELIVERY.SDHNUM_0=STOPREH.SDHNUM_0),1)=1
union
select CREDAT_0, STOFCY_0, PRHNUM_0, PRLNUM_0, SDHNUM_0, isnull((SELECT top 1 ORINUM_0 FROM STOPRELIS WHERE STOPRELIS.PRHNUM_0=STOPREH.PRHNUM_0),''), '3.Deliver' as [Next Step], (SELECT BPCORD_0+','+BPDNAM_0 FROM SORDER WHERE SOHNUM_0=(SELECT top 1 ORINUM_0 FROM STOPRELIS WHERE STOPRELIS.PRHNUM_0=STOPREH.PRHNUM_0)), (SELECT REP_0 FROM SORDER WHERE SOHNUM_0=(SELECT top 1 ORINUM_0 FROM STOPRELIS WHERE STOPRELIS.PRHNUM_0=STOPREH.PRHNUM_0)), (select count(*) from x3.LIVE.STOPRED where PRHNUM_0 = STOPREH.PRHNUM_0) from STOPREH where SDHNUM_0='' and DLVFLG_0<>4
