 ( STOFCY_0 , ORDDAT_0 , SOHNUM_0 , SOQSEQ_0 , ITMREF_0 , ITMDES_0 , QTY_0 
 , SAU_0 , SAUSTUCOE_0 , QTYSTU_0 , STU_0 , YMONKCOST_0 , YB2BBPS_0 
 , ORDMINAMT_0 , FMINUM_0 , FMI_0 ) As 
SELECT a.STOFCY_0 as STOFCY_0 , c.ORDDAT_0 as ORDDAT_0 , c.SOHNUM_0 as SOHNUM_0, SOQSEQ_0, a.ITMREF_0, d.ITMDES_0 as ITMDES_0 ,  
QTY_0, SAU_0, SAUSTUCOE_0,  QTYSTU_0, STU_0, YMONKCOST_0, YB2BBPS_0, ORDMINAMT_0, FMINUM_0, FMI_0
FROM SORDERQ a
INNER JOIN BPSUPPLIER b
ON 
b.BPSNUM_0 = a.YB2BBPS_0
INNER JOIN SORDER c
ON 
c.SOHNUM_0 = a.SOHNUM_0
INNER JOIN SORDERP d
ON
d.SOHNUM_0 = a.SOHNUM_0 and
d.SOPLIN_0 = a.SOPLIN_0 and
d.SOPSEQ_0 = a.SOQSEQ_0
WHERE c.ORDDAT_0>DATEADD(d,-365,GETDATE()) and
b.BPSNUM_0 = a.YB2BBPS_0  and
FMINUM_0 ='' and  FMI_0 <>1 and
ORDSTA_0 = 1 and CDTSTA_0 = 1 and HLDSTA_0  = 1
