 ( CREDAT_0 , STOFCY_0 , SRHNUM_0 , BPCORD_0 , BPDNAM_0 , ITMREF_0 , ITMDES_0 
 , EXTQTYSTU_0 , STU_0 , NOMUSR_0 ) As 
SELECT
SRH.CREDAT_0,
SRH.STOFCY_0,
SRH.SRHNUM_0,
SRH.BPCORD_0,
SRH.BPDNAM_0,
SRD.ITMREF_0,
SRD.ITMDES_0,
SUM(SRD.EXTQTYSTU_0),
SRD.STU_0,
UPPER((SELECT
NOMUSR_0
FROM LIVE.AUTILIS
WHERE USR_0 = SRH.CREUSR_0
))
FROM LIVE.SRETURND SRD
LEFT OUTER JOIN LIVE.SRETURN SRH ON
SRD.SRHNUM_0 = SRH.SRHNUM_0
WHERE QTY_0 = 0
GROUP BY SRH.CREDAT_0,
SRH.STOFCY_0,
SRH.SRHNUM_0,
SRH.BPCORD_0,
SRH.BPDNAM_0,
SRD.ITMREF_0,
SRD.ITMDES_0,
SRD.STU_0,
SRH.CREUSR_0
