 ( ITMREF_0 , STOFCY_0 ) As 
SELECT  QRY.ITMREF_0, QRY.STOFCY_0
FROM (
	SELECT DISTINCT ITD.ITMREF_0, ITH.FCYFROM_0 STOFCY_0 
	FROM LIVE.XINFITD ITD
	LEFT OUTER JOIN LIVE.XINFITH ITH ON ITD.VCRNUM_0=ITH.VCRNUM_0) QRY 
LEFT OUTER JOIN LIVE.ITMFACILIT ITF ON QRY.ITMREF_0=ITF.ITMREF_0 AND QRY.STOFCY_0=ITF.STOFCY_0
LEFT OUTER JOIN LIVE.ITMMASTER ITM ON ITM.ITMREF_0=QRY.ITMREF_0
WHERE ITF.STOFCY_0 IS NULL
