UPDATE LIVE.SINVOICEV SET INVSTA_0=1 where NUM_0='INVOICENUM'
DELETE from LIVE.GACCENTRY WHERE NUM_0='INVOICENUM'
DELETE from LIVE.GACCENTRYD WHERE NUM_0='INVOICENUM'
DELETE from LIVE.TRCVCRDOC WHERE NUM_0='INVOICENUM'