 ( STOFCY_0 , ITMREF_0 , ATS_0 , INWHS_0 , INRECV_0 ) As 
SELECT
ITV.STOFCY_0,
ITV.ITMREF_0,
ITV.PHYSTO_0-ITV.SALSTO_0 - (ITV.PLFCTLSTO_0+ITV.PLFPHYSTO_0+PLFREJSTO_0) AS 'Available To Sell',
ITV.PHYSTO_0- (ITV.PLFCTLSTO_0+ITV.PLFPHYSTO_0+PLFREJSTO_0) AS 'In Whs',
(ITV.PLFCTLSTO_0+ITV.PLFPHYSTO_0+PLFREJSTO_0) AS 'InRecv'
FROM LIVE.ITMMVT ITV
