 ( NUM_0 , BCPST_0 , GST_0 , HST_0 , TAX_0 ) As 
 SELECT NUM_0, ISNULL(( SELECT TOTAL_0 FROM  YFUELCHARGE2 WHERE  VCRNUM_0  = S.NUM_0 AND VAT_0 = 'BCPST' AND DTAVAT_0 <> 'GST'),0)   AS BCPST,  
               ISNULL(( SELECT TOTAL_0 FROM   YFUELCHARGE2 WHERE  VCRNUM_0  = S.NUM_0 AND VAT_0 = 'GST' ),0) AS GST, 
               ISNULL(( SELECT TOTAL_0 FROM   YFUELCHARGE2 WHERE  VCRNUM_0 = S.NUM_0 AND VAT_0 = 'HST'),0)  AS HST,
			   ISNULL(( SELECT TOTAL_0 FROM   YFUELCHARGE2 WHERE  VCRNUM_0 = S.NUM_0 AND VAT_0 = 'TAX'),0)  AS TAX 
 FROM SINVOICE S
