 ( ORDDAT_0 , SOHNUM_0 , BPCNAM_0 , DRN_0 , CNDNAM_0 , TEL_0 , PODAT_0 
 , RCPDAT_0 , ALLPOSCUT_0 , ESTINSTHRS_0 , YCUSTCONT_0 , YINSTALLDATE_0 ) As 
SELECT ORDDAT_0, SOHNUM_0, BPCNAM_0,DRN_0,
YCONTNAME_0, YCONTPHONE_0,
(SELECT TOP 1 ORDDAT_0 FROM PORDERQ WHERE SOHNUM_0=SORDER.SOHNUM_0 ORDER BY 1 DESC) AS [ORDERDATE], 
(SELECT TOP 1 EXTRCPDAT_0 FROM PORDERQ WHERE SOHNUM_0=SORDER.SOHNUM_0 ORDER BY 1 DESC) AS [RECEIPTDATE],
CASE WHEN (SELECT COUNT(*) FROM SORDERQ WHERE SORDERQ.SOHNUM_0=SORDER.SOHNUM_0 AND SORDERQ.FMI_0>1 AND SORDERQ.FMINUM_0='')>0 THEN 1 ELSE 2 END AS [ALLORDERSPLACED],
(SELECT SUM(QTY_0*ITMMASTER.YINSTALLTIME_0) FROM SORDERQ, ITMMASTER WHERE ITMMASTER.ITMREF_0=SORDERQ.ITMREF_0 AND SORDERQ.SOHNUM_0=SORDER.SOHNUM_0) AS [ESTINSTALLTIME],
YCUSTCONT_0, YINSTALLDATE_0
FROM SORDER 
WHERE STOFCY_0='DC31' AND ORDSTA_0=1
GROUP BY ORDDAT_0, SOHNUM_0, BPCNAM_0, DRN_0, YCONTNAME_0, YCONTPHONE_0, YCUSTCONT_0, YINSTALLDATE_0
