 ( RCPFCY_0 , RCPDAT_0 , NUMPOS_0 , LINEAMT_0 , NUMLIN_0 , ORDS_0 ) As 
SELECT        PORDERQ.PRHFCY_0, PORDERQ.EXTRCPDAT_0, COUNT(DISTINCT PORDERQ.POHNUM_0) AS NUMORDS, SUM(PORDERQ.LINAMT_0) AS LINEAMT, COUNT(PORDERQ.POPLIN_0) AS NUMLINS,
CONVERT(VARCHAR(250),(SELECT ',' + PQ.POHNUM_0 
          FROM PORDERQ PQ
          WHERE PQ.EXTRCPDAT_0 = PORDERQ.EXTRCPDAT_0 and PQ.PRHFCY_0=PORDERQ.PRHFCY_0
          ORDER BY POHNUM_0
          FOR XML PATH(''))) [ords]
FROM            PORDERQ INNER JOIN
                         PORDER ON PORDERQ.POHNUM_0 = PORDER.POHNUM_0
WHERE        (PORDERQ.LINCLEFLG_0 = 1) AND PORDER.BETFCY_0=1
GROUP BY PORDERQ.PRHFCY_0, PORDERQ.EXTRCPDAT_0
