 ( CREDAT_0 , BPCNUM_0 , ACCNCKNAM_0 , VCRNUM_0 , FLAG_0 , ACCL4D_0 , AUTID_0 
 , AUTMSG_0 , AUTAMT_0 , ORIGAUTH_0 , TXNID_0 , VPSTXID_0 , VANREF_0 ) As 
SELECT
SOH.CREDAT_0,
SEU.BPCNUM_0,
SEU.ACCNCKNAM_0,
SEU.VCRNUM_0,
CASE SEU.STAFLG_0
WHEN 1 THEN 'SELECTED'
WHEN 2 THEN 'VERIFIED'
WHEN 3 THEN 'AUTHORIZED'
WHEN 4 THEN 'REJECTED'
WHEN 5 THEN 'VOIDED'
WHEN 6 THEN 'CAPTURED'
WHEN 7 THEN 'SETTLED'
WHEN 8 THEN 'MANUAL'
END,
SEU.ACCL4D_0,
SEU.AUTID_0,
SEU.AUTMSG_0,
SEU.AUTAMT_0,
SEU.ORIGAUTH_0,
SEU.TXNID_0,
SEU.VPSTXID_0,
SEU.VANREF_0
FROM LIVE.SEAUTH SEU 
LEFT OUTER JOIN LIVE.SORDER SOH ON
SEU.VCRNUM_0 = SOH.SOHNUM_0
WHERE LEFT(VCRNUM_0,3) IN ('WEB','ORD')
AND SEU.STAFLG_0 = 5
AND SOH.PTE_0 = 'CREDITCARDP'
AND SOH.CREDAT_0 >= '20250107'
AND SEU.SDHNUM_0 = ''
