 ( CREDAT_0 , NUM_0 , BPCORD_0 , BPDNAM_0 , TEL_0 , WEB_0 , PTE_0 ) As 
SELECT
SIH.CREDAT_0,
SIH.NUM_0,
SIV.BPCORD_0,
SIV.BPDNAM_0,
(
SELECT
TEL_0
FROM LIVE.BPADDRESS
WhERE BPANUM_0 = SIV.BPCORD_0
AND BPAADDFLG_0 = 2
),
(
SELECT
WEB_0
FROM LIVE.BPADDRESS
WhERE BPANUM_0 = SIV.BPCORD_0
AND BPAADDFLG_0 = 2
),
SIH.PTE_0
FROM LIVE.SINVOICE SIH
LEFT OUTER JOIN LIVE.SINVOICEV SIV
ON SIH.NUM_0 = SIV.NUM_0
LEFT OUTER JOIN LIVE.SEAUTH SEU ON
SIH.NUM_0 = SEU.SIHNUM_0
WHERE SIH.PTE_0 = 'CREDITCARDP' AND SEU.SIHNUM_0 IS NULL
