 ( SOHNUM_0 , ORDDAT_0 , FIY_0 , PER_0 ) As 
select SOHNUM_0, ORDDAT_0, F.FIYNUM_0, P.PERNUM_0 from SORDER, FISCALYEAR F, PERIOD P WHERE F.FIYSTR_0 <= ORDDAT_0 and F.FIYEND_0 >= ORDDAT_0
and P.PERSTR_0 <= ORDDAT_0 and P.PEREND_0 >= ORDDAT_0
