-- Declare a table variable to hold the NUM_0 values
DECLARE @Nums TABLE (NUM_0 VARCHAR(20));

-- Insert the values once
INSERT INTO @Nums (NUM_0)
VALUES 
('SCM016157');

-- Now use this variable in all your statements
UPDATE LIVE.SINVOICEV 
SET INVSTA_0 = 1
WHERE NUM_0 IN (SELECT NUM_0 FROM @Nums);

--UPDATE LIVE.SINVOICE 
--SET PTE_0 = 'NET30'
--WHERE NUM_0 IN (SELECT NUM_0 FROM @Nums);

DELETE FROM LIVE.GACCENTRY 
WHERE NUM_0 IN (SELECT NUM_0 FROM @Nums);

DELETE FROM LIVE.GACCENTRYD 
WHERE NUM_0 IN (SELECT NUM_0 FROM @Nums);

DELETE FROM LIVE.GACCENTRYA 
WHERE NUM_0 IN (SELECT NUM_0 FROM @Nums);

DELETE FROM LIVE.TRCVCRDOC 
WHERE NUM_0 IN (SELECT NUM_0 FROM @Nums);

DELETE FROM LIVE.GACCTMP 
WHERE NUM_0 IN (SELECT NUM_0 FROM @Nums);

DELETE FROM LIVE.GACCTMPA 
WHERE NUM_0 IN (SELECT NUM_0 FROM @Nums);

DELETE FROM LIVE.GACCTMPD 
WHERE NUM_0 IN (SELECT NUM_0 FROM @Nums);