SELECT
SOH.CREDAT_0,
SOH.SOHNUM_0,
SOH.CUSORDREF_0,
ISNULL((
SELECT
POH.ORDREF_0
FROM LIVE.PORDER POH
WHERE POH.POHNUM_0=SOH.CUSORDREF_0
),''),
ITM.ITMREF_0,
ITM.ITMDES1_0+' '+ITM.ITMDES2_0,
  CAST (SOQ.QTY_0 AS INT) AS 'ORDERED', 
  CAST (
    SOQ.QTY_0 -(SOQ.DLVQTY_0 + SOQ.OPRQTY_0) AS INT
  ) AS 'REMAINING', 
  CAST(SOQ.ALLQTY_0 AS INT) AS 'ALLOCATED', 
  SOP.SAU_0,
  CASE 
  WHEN SOH.SHIDAT_0 > GETDATE() THEN 'FUTURE DELIVERY' 
  WHEN  SOQ.ALLQTY_0 < (
    SELECT SUM(QTYSTU_0 - CUMALLQTY_0) 
    FROM LIVE.STOCK 
    WHERE ITMREF_0 = SOQ.ITMREF_0 
    AND STOFCY_0 = SOQ.STOFCY_0
    AND STA_0 = 'A'
  ) THEN 'UNALLOCATED'
  ELSE 'BACKORDERED'
  END AS 'LINE STATUS',
isnull((SELECT TOP 1
BPS.BPSNAM_0+' - '+BPS.BPSNUM_0
FROM LIVE.BPSUPPLIER BPS
LEFT OUTER JOIN LIVE.ITMBPS ITP ON BPS.BPSNUM_0 = ITP.BPSNUM_0
WHERE ITP.PIO_0=0 and ITP.ITMREF_0=ITM.ITMREF_0
),''),
isnull((SELECT TOP 1
BPS.BPSNAM_0+' - '+BPS.BPSNUM_0
FROM LIVE.BPSUPPLIER BPS
LEFT OUTER JOIN LIVE.ITMBPS ITP ON BPS.BPSNUM_0 = ITP.BPSNUM_0
WHERE ITP.PIO_0<>0 and ITP.ITMREF_0=ITM.ITMREF_0
order by ITP.PIO_0 asc
),''),
isnull(ITM.TSICOD_0,''),
isnull((SELECT
TEXTE_0
FROM LIVE.ATEXTRA
WHERE CODFIC_0='ATABDIV' 
AND IDENT1_0='21' 
AND ZONE_0='LNGDES' 
AND LANGUE_0='ENG'
and IDENT2_0=ITM.TSICOD_1
),''),
isnull((SELECT
SUM(STO.QTYSTU_0)
FROM LIVE.STOCK STO
WHERE STO.ITMREF_0=ITM.ITMREF_0
and STO.STOFCY_0='DC30'
),0) AS 'DC30 OH',
isnull((SELECT
SUM(STO.QTYSTU_0)
FROM LIVE.STOCK STO
WHERE STO.ITMREF_0=ITM.ITMREF_0
and STO.STOFCY_0='1600'
),0) AS 'COURT. OH',
isnull((SELECT
SUM(STO.QTYSTU_0)
FROM LIVE.STOCK STO
WHERE STO.ITMREF_0=ITM.ITMREF_0
and STO.STOFCY_0='2100'
),0) AS 'FORT OH',
isnull((SELECT
SUM(STO.QTYSTU_0)
FROM LIVE.STOCK STO
WHERE STO.ITMREF_0=ITM.ITMREF_0
and STO.STOFCY_0='2200'
),0) AS 'OAK OH',
isnull((SELECT
SUM(STO.QTYSTU_0)
FROM LIVE.STOCK STO
WHERE STO.ITMREF_0=ITM.ITMREF_0
and STO.STOFCY_0='2300'
),0) AS 'BROAD OH',
isnull((SELECT
SUM(STO.QTYSTU_0)
FROM LIVE.STOCK STO
WHERE STO.ITMREF_0=ITM.ITMREF_0
and STO.STOFCY_0='2600'
),0) AS 'SIDNEY OH',
isnull((SELECT
SUM(STO.QTYSTU_0)
FROM LIVE.STOCK STO
WHERE STO.ITMREF_0=ITM.ITMREF_0
),0) AS 'TOTAL OH',
isnull((SELECT
SUM(SID.AMTNOTLIN_0)
FROM LIVE.SINVOICED SID
WHERE SID.ITMREF_0=ITM.ITMREF_0
AND CREDAT_0 >= '20240710'
),0),
ITM.CREDAT_0,
  (
    SELECT 
      CASE WHEN EXISTS (
        SELECT 
          TOP 1 POHNUM_0 
        FROM 
          LIVE.PORDERQ 
        WHERE 
          ITMREF_0 = SOQ.ITMREF_0 
          AND LEFT(POHNUM_0,3)='PO3'
          AND LEFT(BPSNUM_0,1)='V'
          AND LINCLEFLG_0 = 1 
        ORDER BY 
          EXTRCPDAT_0 ASC
      ) THEN (
        SELECT 
          TOP 1 POHNUM_0 
        FROM 
          LIVE.PORDERQ 
        WHERE 
          ITMREF_0 = SOQ.ITMREF_0 
          AND LEFT(POHNUM_0,3)='PO3'
          AND LEFT(BPSNUM_0,1)='V'
          AND LINCLEFLG_0 = 1 
        ORDER BY 
          EXTRCPDAT_0 ASC
      ) ELSE 'N/A' END
  ) AS 'EARLIEST PO', 
  (
    SELECT 
      CASE WHEN EXISTS (
        SELECT 
          TOP 1 CONVERT(VARCHAR, EXTRCPDAT_0, 101) 
        FROM 
          LIVE.PORDERQ 
        WHERE 
          ITMREF_0 = SOQ.ITMREF_0 
          AND LEFT(POHNUM_0,3)='PO3'
          AND LEFT(BPSNUM_0,1)='V'
          AND LINCLEFLG_0 = 1 
        ORDER BY 
          EXTRCPDAT_0 ASC
      ) THEN (
        SELECT 
          TOP 1 CONVERT(VARCHAR, EXTRCPDAT_0, 101) 
        FROM 
          LIVE.PORDERQ 
        WHERE 
          ITMREF_0 = SOQ.ITMREF_0 
          AND LEFT(POHNUM_0,3)='PO3'
          AND LEFT(BPSNUM_0,1)='V'
          AND LINCLEFLG_0 = 1 
        ORDER BY 
          EXTRCPDAT_0 ASC
      ) ELSE 'N/A' END
  ) AS 'ETA', 
  (
    SELECT 
      CASE WHEN EXISTS (
        SELECT 
          TOP 1 BPS1.BPSNAM_0 + ' - ' + POQ1.BPSNUM_0 
        FROM 
          LIVE.PORDERQ POQ1 
          LEFT OUTER JOIN LIVE.BPSUPPLIER BPS1 ON POQ1.BPSNUM_0 = BPS1.BPSNUM_0 
        WHERE 
          ITMREF_0 = SOQ.ITMREF_0 
          AND LEFT(POQ1.POHNUM_0,3)='PO3' 
          AND LEFT(POQ1.BPSNUM_0,1)='V' 
          AND POQ1.LINCLEFLG_0 = 1 
        ORDER BY 
          POQ1.EXTRCPDAT_0 ASC
      ) THEN (
        SELECT 
          TOP 1 BPS2.BPSNAM_0 + ' - ' + POQ2.BPSNUM_0 
        FROM 
          LIVE.PORDERQ POQ2 
          LEFT OUTER JOIN LIVE.BPSUPPLIER BPS2 ON POQ2.BPSNUM_0 = BPS2.BPSNUM_0 
        WHERE 
          ITMREF_0 = SOQ.ITMREF_0 
          AND LEFT(POQ2.POHNUM_0,3)='PO3' 
          AND LEFT(POQ2.BPSNUM_0,1)='V' 
          AND POQ2.LINCLEFLG_0 = 1 
        ORDER BY 
          POQ2.EXTRCPDAT_0 ASC
      ) ELSE 'N/A' END
  ) AS 'PO VENDOR'


FROM LIVE.ITMMASTER ITM
LEFT OUTER JOIN LIVE.SORDERQ SOQ ON ITM.ITMREF_0=SOQ.ITMREF_0
LEFT OUTER JOIN LIVE.SORDERP SOP ON SOQ.ITMREF_0=SOP.ITMREF_0 AND SOQ.SOPLIN_0=SOP.SOPLIN_0 AND SOQ.SOQSEQ_0=SOP.SOPSEQ_0 AND SOQ.SOHNUM_0=SOP.SOHNUM_0
LEFT OUTER JOIN LIVE.SORDER SOH ON SOQ.SOHNUM_0=SOH.SOHNUM_0

WHERE SOH.BETFCY_0=2 AND SOH.BPAADD_0='STORE' AND LEFT(SOH.CREUSR_0,3)='MOR' AND LEFT(SOH.CREUSR_0,4)<>'MORF' AND SOQ.SOQSTA_0<>3 AND (SOQ.QTYSTU_0-(SOQ.ALLQTYSTU_0+SOQ.PREQTYSTU_0+SOQ.DLVQTYSTU_0) > 0 AND SOQ.QTYSTU_0-(SOQ.ALLQTYSTU_0+SOQ.OPRQTYSTU_0+SOQ.TDLQTYSTU_0) > 0
  AND SOQ.QTYSTU_0-(SOQ.ALLQTYSTU_0+SOQ.PREQTYSTU_0+SOQ.TDLQTYSTU_0) > 0)