SELECT
SID.ITMREF_0 AS 'MONK CODE',
PTD.BPSNUM+' - '+BPS.BPSNAM AS 'LAST RCP. BEFORE INV. DAT. SUPPLIER',
ITP.ITMREFBPS AS 'LAST RCP. BEFORE INV. DAT. SUPPLIER CODE',
CASE BPS.BPRPAY
	WHEN 'V5555' THEN 'YES' ELSE 'NO'
END AS 'BASICS',
'' AS 'ManufacturerBrand',
'' AS 'ManufacturerNumber',
SID.ITMDES_0 AS 'Description',
SID.QTY_0 AS 'Quantity_Sold',
FORMAT(SID.CREDAT_0, 'M/d/yyyy') as 'InvoiceDate',
CASE LEFT(SID.SOHNUM_0,3)
	WHEN 'WEB' THEN 'Y' ELSE 'N'
END AS 'Online_Flag'

FROM LIVE.SINVOICED SID
OUTER APPLY (
    SELECT TOP 1
        ITMREF_0,
        BPSNUM_0 AS BPSNUM
    FROM 
        LIVE.PRECEIPTD
    WHERE 
        LEFT(BPSNUM_0, 1) = 'V' 
        AND CREDAT_0 <= SID.CREDAT_0
        AND ITMREF_0 = SID.ITMREF_0
    ORDER BY 
        CREDAT_0 DESC
) PTD
LEFT OUTER JOIN (
	SELECT
		ITMREF_0,
		BPSNUM_0,
		ITMREFBPS_0 AS ITMREFBPS
	FROM
		LIVE.ITMBPS
) ITP ON PTD.BPSNUM = ITP.BPSNUM_0 and PTD.ITMREF_0 = ITP.ITMREF_0

LEFT OUTER JOIN (
	SELECT
		BPSNUM_0,
		BPSNAM_0 AS BPSNAM,
		BPRPAY_0 AS BPRPAY
	FROM 
		LIVE.BPSUPPLIER
) BPS ON PTD.BPSNUM = BPS.BPSNUM_0
left outer join LIVE.ITMMASTER ITM ON SID.ITMREF_0 = ITM.ITMREF_0

WHERE SID.CREDAT_0 BETWEEN '20240801' and '20250131' and (LEFT(SID.ITMREF_0,3) IN ('CTG','DPS','HEW') or (left(SID.ITMREF_0,3)='BAS' and ITM.TSICOD_1='3184'))

order by SID.CREDAT_0 ASC