SELECT
ITP.ITMREF_0 as [Product],
ITP.BPSNUM_0 as [Supplier],
ITP.PIO_0 as [Priority],
ITM.ITMDES1_0 as [Description],
ITM.SEAKEY_0 as [Basics Code],
ITM.EANCOD_0 as [UPC],
ITM.TSICOD_0 as [Monk Status]
FROM LIVE.ITMBPS ITP
LEFT JOIN LIVE.ITMMASTER ITM ON ITP.ITMREF_0=ITM.ITMREF_0


WHERE BPSNUM_0 IN ('V2027','V2028')
