SELECT
CONVERT(VARCHAR,CUN.CREDAT_0,101) AS 'DATE CREATED',
CUN.STOFCY_0 as 'STOCK SITE',
CUD.CUNSSSNUM_0 AS 'SESSION',
CUN.CUNSSSDES_0 AS 'DESCRIPTION',
CASE
WHEN CUN.CUNSSSSTA_0 = 1 THEN 'In creation'
WHEN CUN.CUNSSSSTA_0 = 2 THEN 'To be counted'
WHEN CUN.CUNSSSSTA_0 = 3 THEN 'Closed'
END AS 'STATUS',
COUNT(CUD.ITMREF_0) AS 'LINES'

FROM LIVE.CUNLISDET CUD
LEFT OUTER JOIN LIVE.CUNSESSION CUN ON CUD.CUNSSSNUM_0 = CUN.CUNSSSNUM_0

GROUP BY CUN.CREDAT_0, CUN.STOFCY_0, CUD.CUNSSSNUM_0, CUN.CUNSSSDES_0,CUN.CUNSSSSTA_0

ORDER BY CUN.CREDAT_0 desc