SELECT
isnull(ATX.TEXTE_0,'NO CLASS') as ClassName,
COUNT(ITM.ITMREF_0) as ProductCount

From LIVE.ITMMASTER ITM
LEFT JOIN LIVE.ATEXTRA ATX ON ATX.CODFIC_0 = 'ATABDIV'
    AND ATX.IDENT1_0 = '21'
    AND ATX.ZONE_0 = 'LNGDES'
    AND ATX.LANGUE_0 = 'ENG'
    AND ATX.IDENT2_0 = ITM.TSICOD_1

Group by ATX.TEXTE_0
order by ATX.TEXTE_0 Asc