With SalesData as (
    SELECT
        ITMREF_0,
        -- SUM AMTNOTLIN_0 FROM TODAY'S DATE (DATE FIELD = INVDAT_0)
        SUM(CASE WHEN INVDAT_0 = GETDATE() THEN AMTNOTLIN_0 ELSE 0 END) AS SalesToday,
        -- SUM AMTNOTLIN_0 WITH LAST WEEK OF DATA NOT INCLUDING TODAY
        SUM(CASE WHEN INVDAT_0 >= DATEADD(wk, -1, GETDATE()) AND INVDAT_0 < GETDATE() THEN AMTNOTLIN_0 ELSE 0 END) AS SalesLastWeek,
        -- SUM AMTNOTLIN_0 WITH 1 WEEK OF DATA BEGINNING 2 WEEKS AGO
        SUM(CASE WHEN INVDAT_0 >= DATEADD(wk, -2, GETDATE()) AND INVDAT_0 < DATEADD(wk, -1, GETDATE()) THEN AMTNOTLIN_0 ELSE 0 END) AS Sales2WeeksAgo,
        -- SUM AMTNOTLIN_0 WITH 1 WEEK OF DATA BEGINNING 3 WEEKS AGO
        SUM(CASE WHEN INVDAT_0 >= DATEADD(wk, -3, GETDATE()) AND INVDAT_0 < DATEADD(wk, -2, GETDATE()) THEN AMTNOTLIN_0 ELSE 0 END) AS Sales3WeeksAgo,
        -- SUM AMTNOTLIN_0 WITH 1 WEEK OF DATA BEGINNING 4 WEEKS AGO
        SUM(CASE WHEN INVDAT_0 >= DATEADD(wk, -4, GETDATE()) AND INVDAT_0 < DATEADD(wk, -3, GETDATE()) THEN AMTNOTLIN_0 ELSE 0 END) AS Sales4WeeksAgo,
		SUM(CASE WHEN INVDAT_0 >= DATEADD(wk, -4, GETDATE()) THEN AMTNOTLIN_0 ELSE 0 END) AS Sales4WeekTotal
    FROM LIVE.SINVOICED
    GROUP BY
        ITMREF_0
),
StockData as (
	SELECT
		ITMREF_0,
		SUM(CASE WHEN STOFCY_0='DC30' THEN QTYSTU_0 ELSE 0 END) as StockDC30,
		SUM(CASE WHEN STOFCY_0='1600' THEN QTYSTU_0 ELSE 0 END) as Stock1600,
		SUM(CASE WHEN STOFCY_0='2100' THEN QTYSTU_0 ELSE 0 END) as Stock2100,
		SUM(CASE WHEN STOFCY_0='2200' THEN QTYSTU_0 ELSE 0 END) as Stock2200,
		SUM(CASE WHEN STOFCY_0='2300' THEN QTYSTU_0 ELSE 0 END) as Stock2300,
		SUM(CASE WHEN STOFCY_0='2600' THEN QTYSTU_0 ELSE 0 END) as Stock2600,
		SUM(QTYSTU_0) AS TotalStock
	FROM LIVE.STOCK
	GROUP BY
		ITMREF_0
)

SELECT DISTINCT
    SPL.PLICRD_0 as [Product],
	ITM.ITMDES1_0 as [Description],
	ITM.TSICOD_0 as [Status],
	isnull(STK.StockDC30,0) as [Stock DC30],
	isnull(STK.Stock1600,0) as [Stock 1600],
	isnull(STK.Stock2100,0) as [Stock 2100],
	isnull(STK.Stock2200,0) as [Stock 2200],
	isnull(STK.Stock2300,0) as [Stock 2300],
	isnull(STK.Stock2600,0) as [Stock 2600],
	isnull(STK.TotalStock,0) as [Total Stock],
	ITM.STU_0 as [Unit],
    isnull(SD.SalesToday,0) as [Today],
    isnull(SD.SalesLastWeek,0) as [Week 1],
    isnull(SD.Sales2WeeksAgo,0) as [Week 2],
    isnull(SD.Sales3WeeksAgo,0) as [Week 3],
    isnull(SD.Sales4WeeksAgo,0) as [Week 4],
	isnull(SD.Sales4WeekTotal,0) as [Total]
FROM LIVE.SPRICLIST SPL
LEFT JOIN SalesData SD ON SPL.PLICRD_0 = SD.ITMREF_0
LEFT JOIN LIVE.ITMMASTER ITM ON SPL.PLICRD_0=ITM.ITMREF_0
LEFT JOIN StockData STK ON SPL.PLICRD_0=STK.ITMREF_0
WHERE SPL.PLI_0 = '107'