With StockQty as (
	SELECT
		ITMREF_0,
		SUM(CASE WHEN STOFCY_0='1600' THEN QTYSTU_0-CUMALLQTY_0 ELSE 0 END) AS [Stk16],
		SUM(CASE WHEN STOFCY_0='2100' THEN QTYSTU_0-CUMALLQTY_0 ELSE 0 END) AS [Stk21],
		SUM(CASE WHEN STOFCY_0='2200' THEN QTYSTU_0-CUMALLQTY_0 ELSE 0 END) AS [Stk22],
		SUM(CASE WHEN STOFCY_0='2300' THEN QTYSTU_0-CUMALLQTY_0 ELSE 0 END) AS [Stk23],
		SUM(CASE WHEN STOFCY_0='2600' THEN QTYSTU_0-CUMALLQTY_0 ELSE 0 END) AS [Stk26],
		SUM(CASE WHEN STOFCY_0='DC30' THEN QTYSTU_0-CUMALLQTY_0 ELSE 0 END) AS [DC30],
		SUM(CASE WHEN STOFCY_0='DC33' THEN QTYSTU_0-CUMALLQTY_0 ELSE 0 END) AS [DC33]
	FROM
		LIVE.STOCK
	GROUP BY ITMREF_0
)

SELECT
	SOH.STOFCY_0 as [Site],
	SOH.SOHNUM_0 as [Sales Order],
	SOQ.ITMREF_0 as [Product],
	ITM.ITMDES1_0 as [Description],
	SOH.BPCORD_0 as [Customer],
	SOH.BPCNAM_0 as [Name],
	SOH.SHIDAT_0 as [Shipping Date],
	SOQ.QTYSTU_0 as [Ordered],
	SOQ.ALLQTYSTU_0 as [Allocated],
	ITM.SAU_0 as [Unit],
	STK.Stk16 as [Stk 16],
	STK.Stk21 as [Stk 21],
	STK.Stk22 as [Stk 22],
	STK.Stk23 as [Stk 23],
	STK.Stk26 as [Stk 26],
	STK.DC30 as [Stk DC30],
	STK.DC33 as [Stk DC33],
	ITM.RPLITM_0 as [Alternate]

FROM LIVE.SORDER SOH
LEFT OUTER JOIN LIVE.SORDERQ SOQ ON SOH.SOHNUM_0=SOQ.SOHNUM_0
LEFT OUTER JOIN LIVE.ITMMASTER ITM ON SOQ.ITMREF_0=ITM.ITMREF_0
LEFT JOIN StockQty STK ON SOQ.ITMREF_0=STK.ITMREF_0

WHERE SOH.ORDSTA_0=1 and SOH.SHIDAT_0>=GETDATE()
and ITM.ZBTSFLG_0=2

order by [Shipping Date] asc, ITM.ITMREF_0 asc