WITH AVC_CTE AS (
    SELECT ITMREF_0, AVC_0
    FROM LIVE.ITMMVT
    WHERE STOFCY_0 = 'DC30'
),
GROPRI_CTE AS (
    SELECT
        ITMREF_0,
        GROPRI_0,
        ROW_NUMBER() OVER (PARTITION BY ITMREF_0 ORDER BY CREDAT_0 DESC) AS RowNum
    FROM LIVE.PORDERP
    WHERE PRHFCY_0 = 'DC30' AND GROPRI_0 > 0
)
SELECT
    CLD.CUNSSSNUM_0,
    CLD.STOFCY_0,
    SUM(
        CASE
            WHEN CLD.CUNCST_0 > 0 THEN CLD.CUNCST_0 * CLD.QTYSTU_0
            WHEN AVC.AVC_0 > 0 THEN AVC.AVC_0 * CLD.QTYSTU_0
            ELSE COALESCE(GROPRI.GROPRI_0, 0) * CLD.QTYSTU_0
        END
    ) AS Total
FROM
    LIVE.CUNLISDET CLD
LEFT JOIN
    AVC_CTE AVC
    ON CLD.ITMREF_0 = AVC.ITMREF_0
LEFT JOIN
    GROPRI_CTE GROPRI
    ON CLD.ITMREF_0 = GROPRI.ITMREF_0 AND GROPRI.RowNum = 1
WHERE
    CLD.CREDAT_0 = ''
    AND CLD.CREUSR_0 = ''
GROUP BY
    CLD.CUNSSSNUM_0, CLD.STOFCY_0
ORDER BY
CLD.CUNSSSNUM_0 asc;