SELECT
BPRPAY_0,
SUM((SNS_0*(AMTCUR_0-PAYCUR_0)))

FROM LIVE.GACCDUDATE DUD
WHERE DUDDAT_0<='20250430'
AND TYP_0 NOT IN ('NP' , 'NEWPR' , 'NEW' , 'CLO' , 'INT' , '*SO')
AND SAC_0='AR'
AND (SELECT
	YFINCHG_0
	FROM LIVE.BPCUSTOMER
	WHERE BPCNUM_0=DUD.BPR_0)=2
GROUP BY BPRPAY_0 HAVING (SUM(AMTCUR_0-PAYCUR_0)<>0 OR SUM(AMTCUR_0-PAYCUR_0) IS NULL) AND  SUM(SNS_0*(AMTCUR_0-PAYCUR_0))>=1

ORDER BY SUM((AMTCUR_0-PAYCUR_0)) desc