SELECT
D.STOFCY_0 AS 'STOCK SITE',
D.ITMREF_0 AS 'PRODUCT',
I.ITMDES1_0+' '+I.ITMDES2_0 AS 'DESCRIPTION',
B.BPCNUM_0+' - '+B.BPCNAM_0 AS 'CUSTOMER',
S.SOHNUM_0 AS 'SALES ORDER',
CONVERT(VARCHAR,S.ORDDAT_0,101) AS 'DATE ORDERED',
CONVERT(VARCHAR,H.CREDAT_0,101) AS 'DATE PICKED',
DATEDIFF(DAY,S.ORDDAT_0,H.CREDAT_0) AS 'DAYS'




FROM LIVE.SDELIVERYD D
LEFT OUTER JOIN LIVE.SORDER S ON D.SOHNUM_0 = S.SOHNUM_0
LEFT OUTER JOIN LIVE.ITMMASTER I ON D.ITMREF_0 = I.ITMREF_0
LEFT OUTER JOIN LIVE.STOPREH H ON D.PRHNUM_0 = H.PRHNUM_0
LEFT OUTER JOIN LIVE.BPCUSTOMER B ON S.BPCORD_0 = B.BPCNUM_0

WHERE S.STOFCY_0 = 'DC30' AND S.CREDAT_0 >= GETDATE()-60 AND D.ITMREF_0 NOT LIKE '/%' AND S.DME_0 = 1 AND S.DLVPIO_0 = 1 AND DATEDIFF(DAY,S.ORDDAT_0,H.CREDAT_0) >= 4 AND (S.ORDDAT_0 = H.CREDAT_0 OR S.ORDDAT_0+1 = S.CREDAT_0+1)


ORDER BY D.ITMREF_0 ASC