SELECT
FRMNUM_0, 
NUM_0, 
DUDDAT_0,
AMTCUR_0
FROM LIVE.PAYMENTH

WHERE DUDDAT_0 >= CASE
	WHEN MONTH(GETDATE()) BETWEEN 1 AND 6 THEN CONVERT(VARCHAR, YEAR(GETDATE())-1)+'0701'
	ELSE CONVERT(VARCHAR, YEAR(GETDATE()))+'0701'
END
AND DUDDAT_0 <= CASE
	WHEN MONTH(GETDATE()) BETWEEN 1 AND 6 THEN CONVERT(VARCHAR, YEAR(GETDATE()))+'0630'
	ELSE CONVERT(VARCHAR, YEAR(GETDATE())+1)+'0630'
END