select SOHNUM_0, BPCORD_0, SDHNUM_0, SIHNUM_0 FROM LIVE.SDELIVERY WHERE BPCORD_0 = ''
AND CREDAT_0 >= GETDATE()-1

order by SOHNUM_0 asc

--

SELECT DISTINCT STOPRELIS.ORINUM_0, STOPRELIS.PRLNUM_0, STOPRELIS.PRHNUM_0, STOPREH.DLVFLG_0 FROM LIVE.STOPRELIS

LEFT OUTER JOIN LIVE.STOPREH ON STOPRELIS.PRHNUM_0 = STOPREH.PRHNUM_0

WHERE STOPRELIS.BPCORD_0 = ''

order by STOPRELIS.PRLNUM_0 asc
