With Freight AS (
	SELECT
		NUM_0,
		CASE WHEN INVDTA_0=2 THEN INVDTAAMT_0 ELSE 0 END AS FREIGHT_2,
		CASE WHEN INVDTA_0=3 THEN INVDTAAMT_0 ELSE 0 END AS FREIGHT_3
	FROM
		LIVE.PVCRFOOT
	WHERE INVDTA_0 IN (2,3)
)

SELECT TOP 100
PIH.CREDAT_0 as [Date Created],
PIH.NUM_0 as [Number],
PTH.BPSNUM_0 as [Supplier],
PIH.AMTNOT_0 as [Invoice Total -Tax],
FRT.FREIGHT_2+FRT.FREIGHT_3 as [Freight],
ROUND(((FRT.FREIGHT_2+FRT.FREIGHT_3)/PIH.AMTNOT_0),2) as [% of Total]
FROM LIVE.PINVOICED PID
LEFT JOIN LIVE.PRECEIPT PTH ON PID.PTHNUM_0=PTH.PTHNUM_0
LEFT JOIN LIVE.PINVOICE PIH ON PID.NUM_0=PIH.NUM_0
LEFT JOIN Freight FRT ON PIH.NUM_0=FRT.NUM_0
WHERE (FRT.FREIGHT_2+FRT.FREIGHT_3) IS NOT NULL
Group by PIH.CREDAT_0,PIH.NUM_0,PTH.BPSNUM_0,PIH.AMTNOT_0,FRT.FREIGHT_2,FRT.FREIGHT_3



order by PIH.CREDAT_0 DESC