SELECT
(
SELECT
BPCNAM_0
FROM LIVE.BPCUSTOMER
WHERE BPCNUM_0 = SIV.BPCORD_0
) AS 'SHIP-TO NAME',
SIV.BPCINV_0 AS 'BILL-TO BP',
(
SELECT
WEB_0
FROM LIVE.BPADDRESS
WHERE BPANUM_0 = SIV.BPCORD_0 AND BPAADD_0 = 'ADDR'
) AS 'SHIP-TO EMAIL',
(
SELECT
WEB_0
FROM LIVE.BPADDRESS
WHERE BPANUM_0 = SIV.BPCINV_0 AND BPAADD_0 = 'ADDR'
) AS 'BILL-TO EMAIL',
(
SELECT
TEL_0
FROM LIVE.BPADDRESS
WHERE BPANUM_0 = SIV.BPCORD_0 AND BPAADD_0 = 'ADDR'
) AS 'SHIP-TO PHONE',
(
SELECT
TEL_0
FROM LIVE.BPADDRESS
WHERE BPANUM_0 = SIV.BPCINV_0 AND BPAADD_0 = 'ADDR'
) AS 'BILL-TO PHONE'

FROM LIVE.SINVOICED SID
LEFT OUTER JOIN LIVE.SINVOICEV SIV ON SID.NUM_0 = SIV.NUM_0

WHERE SID.ITMREF_0 IN ('COPYBLOCK','LABOUR') AND SIV.CREDAT_0 >= '20231028'

GROUP BY SIV.BPCINV_0, SIV.BPCORD_0


ORDER BY
(
SELECT
BPCNAM_0
FROM LIVE.BPCUSTOMER
WHERE BPCNUM_0 = SIV.BPCORD_0
) ASC