SELECT
SDD.CREDAT_0 AS DatePicked,
SDD.STOFCY_0 AS StockSite,
SDD.PRHNUM_0 AS PickTicket,
SDD.BPCORD_0 AS SoldTo,
SDD.SOHNUM_0 AS SalesOrder,
CASE
WHEN SOH.BETFCY_0=1 THEN 'COMMERCIAL'
WHEN SOH.BETFCY_0=2 THEN 'RETAIL'
ELSE 'SALES ORDER N/A'
END AS SaleOrderType,
SDD.ITMREF_0 AS Product,
SDD.ITMDES1_0 AS Description,
SDD.QTYSTU_0/SDD.SAUSTUCOE_0 AS Quantity,
SOP.SAU_0 AS SalesUnit,
SOP.GROPRI_0 AS SalesPrice,
(SDD.QTYSTU_0/SOP.SAUSTUCOE_0)*SOP.GROPRI_0 AS TotalSales,
ITM.ACCCOD_0 AS AccountingCode


FROM LIVE.SDELIVERYD SDD
LEFT JOIN LIVE.SORDERP SOP ON SDD.SOHNUM_0=SOP.SOHNUM_0 AND SDD.SOPLIN_0=SOP.SOPLIN_0
LEFT JOIN LIVE.SORDER SOH ON SOP.SOHNUM_0=SOH.SOHNUM_0
LEFT JOIN LIVE.ITMMASTER ITM ON SDD.ITMREF_0=ITM.ITMREF_0