WITH SalesPrice AS (
    SELECT
        PLICRI2_0,
        PRI_0,
        ROW_NUMBER() OVER (PARTITION BY PLICRI2_0 ORDER BY MAXQTY_0 ASC) AS rn
    FROM LIVE.SPRICLIST
    WHERE PLI_0 = '11' AND PLICRI1_0 = 'PL2'
),
SalesData AS (
    SELECT
        SID.ITMREF_0,
        SUM(SID.AMTNOTLIN_0 * SIV.SNS_0) AS TotalSales,
		SUM(SID.QTYSTU_0 * SIV.SNS_0) AS TotalSalesQty
    FROM
        LIVE.SINVOICED AS SID
    INNER JOIN
        LIVE.SINVOICE AS SIV ON SID.NUM_0 = SIV.NUM_0
    WHERE
        SID.CREDAT_0 >= DATEADD(year, -1, GETDATE())
    GROUP BY
        SID.ITMREF_0
),
VendorInfo AS (
    SELECT
        ITMREF_0,
        ITP.BPSNUM_0,
        ITP.BPSNUM_0 + ' ' + BPS.BPSNAM_0 AS VendorName,
        ROW_NUMBER() OVER (PARTITION BY ITMREF_0 ORDER BY CASE WHEN PIO_0 = 0 THEN 0 ELSE 1 END, PIO_0) AS VendorRank
    FROM LIVE.ITMBPS ITP
    LEFT JOIN LIVE.BPSUPPLIER BPS ON BPS.BPSNUM_0 = ITP.BPSNUM_0
),
StockData AS (
    SELECT
        STO.ITMREF_0,
        SUM(CASE WHEN STO.STOFCY_0 = 'DC30' THEN STO.QTYSTU_0 ELSE 0 END) AS StockTotalDC30,
        SUM(CASE WHEN STO.STOFCY_0 = '1600' THEN STO.QTYSTU_0 ELSE 0 END) AS StockTotalCourt,
        SUM(CASE WHEN STO.STOFCY_0 = '2100' THEN STO.QTYSTU_0 ELSE 0 END) AS StockTotalFort,
        SUM(CASE WHEN STO.STOFCY_0 = '2200' THEN STO.QTYSTU_0 ELSE 0 END) AS StockTotalOak,
        SUM(CASE WHEN STO.STOFCY_0 = '2300' THEN STO.QTYSTU_0 ELSE 0 END) AS StockTotalBroad,
        SUM(CASE WHEN STO.STOFCY_0 = '2600' THEN STO.QTYSTU_0 ELSE 0 END) AS StockTotalSidney,
        SUM(CASE WHEN STO.STOFCY_0 = '3200' THEN STO.QTYSTU_0 ELSE 0 END) AS StockTotal3200
    FROM LIVE.STOCK STO
    GROUP BY STO.ITMREF_0
),
SafetyStock AS (
	SELECT
		ITMREF_0,
		SUM(CASE WHEN STOFCY_0 = 'DC30' THEN SAFSTO_0 ELSE 0 END) AS SafetyStockDC30,
        SUM(CASE WHEN STOFCY_0 = '1600' THEN SAFSTO_0 ELSE 0 END) AS SafetyStockCOR,
        SUM(CASE WHEN STOFCY_0 = '2100' THEN SAFSTO_0 ELSE 0 END) AS SafetyStockFRT,
        SUM(CASE WHEN STOFCY_0 = '2200' THEN SAFSTO_0 ELSE 0 END) AS SafetyStockOAK,
        SUM(CASE WHEN STOFCY_0 = '2300' THEN SAFSTO_0 ELSE 0 END) AS SafetyStockBRD,
        SUM(CASE WHEN STOFCY_0 = '2600' THEN SAFSTO_0 ELSE 0 END) AS SafetyStockSID,
        SUM(CASE WHEN STOFCY_0 = '3200' THEN SAFSTO_0 ELSE 0 END) AS SafetyStockFRN
	FROM LIVE.ITMFACILIT
	GROUP BY ITMREF_0
)
SELECT
ITM.ITMREF_0 as Product,
ITM.ITMDES1_0+' '+ITMDES2_0 as Description,
ITM.RPLITM_0 as Alternate,
ITM.TSICOD_1 as Class,
ATX.TEXTE_0 as ClassName,
SPL.PRI_0 as PL2Price,
ITM.TSICOD_0 as Status,
isnull(SAL.TotalSales,0) as Sales_1Y,
isnull(SAL.TotalSalesQty,0) as SalesQty_1Y,
MAX(CASE WHEN VI.VendorRank = 1 THEN VI.VendorName ELSE 'N/A' END) AS PrimaryVendor,
MAX(CASE WHEN VI.VendorRank = 2 THEN VI.VendorName ELSE 'N/A' END) AS SecondaryVendor,
ITM.STU_0 as StockUnit,
ISNULL(STD.StockTotalDC30,0) as STK_DC30,
ISNULL(STD.StockTotalCourt,0) as STK_COR,
ISNULL(STD.StockTotalFort,0) as STK_FRT,
ISNULL(STD.StockTotalOak,0) as STK_OAK,
ISNULL(STD.StockTotalBroad,0) as STK_BRD,
ISNULL(STD.StockTotalSidney,0) as STK_SID,
ISNULL(STD.StockTotal3200,0) as STK_FRN,
ISNULL(SAF.SafetyStockDC30,0) as SAF_DC30,
ISNULL(SAF.SafetyStockCOR,0) as SAF_COR,
ISNULL(SAF.SafetyStockFRT,0) as SAF_FRT,
ISNULL(SAF.SafetyStockOAK,0) as SAF_OAK,
ISNULL(SAF.SafetyStockBRD,0) as SAF_BRD,
ISNULL(SAF.SafetyStockSID,0) as SAF_SID,
ISNULL(SAF.SafetyStockFRN,0) as SAF_FRN



FROM LIVE.ITMMASTER ITM
LEFT JOIN LIVE.ATEXTRA ATX ON ATX.CODFIC_0 = 'ATABDIV'
    AND ATX.IDENT1_0 = '21'
    AND ATX.ZONE_0 = 'LNGDES'
    AND ATX.LANGUE_0 = 'ENG'
    AND ATX.IDENT2_0 = ITM.TSICOD_1
LEFT JOIN SalesPrice SPL on ITM.ITMREF_0=SPL.PLICRI2_0 and SPL.rn=1 
LEFT JOIN SalesData SAL on ITM.ITMREF_0=SAL.ITMREF_0
LEFT JOIN VendorInfo VI on ITM.ITMREF_0 = VI.ITMREF_0
LEFT JOIN StockData STD ON ITM.ITMREF_0 = STD.ITMREF_0
LEFT JOIN SafetyStock SAF on ITM.ITMREF_0=SAF.ITMREF_0
GROUP BY
ITM.ITMREF_0,
ITM.ITMDES1_0,
ITM.ITMDES2_0,
ITM.RPLITM_0,
ITM.TSICOD_0,
ITM.TSICOD_1,
ATX.TEXTE_0,
SPL.PRI_0,
SAL.TotalSales,
SAL.TotalSalesQty,
ITM.TSICOD_0,
ITM.STU_0,
STD.StockTotalDC30,
STD.StockTotalCourt,
STD.StockTotalFort,
STD.StockTotalOak,
STD.StockTotalBroad,
STD.StockTotalSidney,
STD.StockTotal3200,
SAF.SafetyStockDC30,
SAF.SafetyStockFRT,
SAF.SafetyStockCOR,
SAF.SafetyStockOAK,
SAF.SafetyStockBRD,
SAF.SafetyStockSID,
SAF.SafetyStockFRN