SELECT
PIN.NUM_0,
CASE
WHEN PIN.GTE_0 IN ('SPINV', 'SPDIR') THEN 'INVOICE'
WHEN PIN.GTE_0 = 'SPMEM' THEN 'CREDIT'
END,
PIN.BPR_0,
PIN.BPRNAM_0,
GDD.DUDDAT_0,
PIN.PTE_0,
GDD.AMTCUR_0,
GDD.PAYCUR_0,
GDD.AMTCUR_0 - GDD.PAYCUR_0,
PIN.CUR_0

FROM LIVE.PINVOICE PIN
LEFT OUTER JOIN LIVE.GACCDUDATE GDD ON
PIN.GTE_0 = GDD.TYP_0 AND PIN.NUM_0 = GDD.NUM_0
LEFT OUTER JOIN LIVE.PAYMENTD PYD ON
PIN.GTE_0 = PYD.VCRTYP_0 AND PIN.NUM_0 = PYD.VCRNUM_0

WHERE PIN.STA_0 = 3 AND PAZ_0 = 4 AND GDD.AMTCUR_0-GDD.PAYCUR_0>0 AND GDD.DUDDAT_0<=CONVERT(VARCHAR,GETDATE(),101) AND PYD.NUM_0 IS NULL