SELECT
SIH.CREDAT_0,
SIH.BPRPAY_0,
SIH.GTE_0,
SIH.AMTATI_0,
SIH.NUM_0,
SIV.SIHORINUM_0,
PYD.NUM_0,
HAE.NUM_0

FROM LIVE.SINVOICE SIH
LEFT JOIN LIVE.GACCENTRY HAE ON SIH.NUM_0=HAE.NUM_0 AND SIH.GTE_0=HAE.TYP_0
LEFT JOIN LIVE.PAYMENTD PYD ON SIH.NUM_0=PYD.VCRNUM_0
LEFT JOIN LIVE.SINVOICEV SIV ON SIH.NUM_0=SIV.NUM_0
WHERE HAE.NUM_0 IS NULL