SELECT
    SIV.CREDAT_0 AS CREATIONDATE,
    SIV.REP_0 AS REPNUM,
    REP.REPNAM_0 AS REPNAME,
    SIV.SALFCY_0 AS SALESSITE,
    SIV.BPRPAY_0 AS BPRPAY,
    BPC.BPCNAM_0 AS BPRPAYNAM,
    SIV.BPCORD_0 AS SHIPTOCODE,
    SIV.BPDNAM_0 AS SHIPTONAM,
    SID.ITMREF_0 AS PRODUCTREF,
    SID.ITMDES_0 AS PRODUCTDES,
    SIV.NUM_0 AS INVOICENUM,
    CASE
        WHEN SID.SOHNUM_0 = '' THEN (
            SELECT TOP 1 SOH.SOHNUM_0
            FROM LIVE.SORDER SOH
            WHERE SOH.SOHNUM_0 = (
                SELECT TOP 1 SDD.SOHNUM_0
                FROM LIVE.SDELIVERYD SDD
                WHERE SDD.SDHNUM_0 = (
                    SELECT TOP 1 SRD.SDHNUM_0
                    FROM LIVE.SRETURND SRD
                    WHERE SRD.SIHNUM_0 = SID.NUM_0 AND SRD.SIDLIN_0 = SID.SIDLIN_0
                )
                AND SDD.SDDLIN_0 = (
                    SELECT TOP 1 SRD.SDDLIN_0
                    FROM LIVE.SRETURND SRD
                    WHERE SRD.SIHNUM_0 = SID.NUM_0 AND SRD.SIDLIN_0 = SID.SIDLIN_0
                )
            )
        )
        ELSE SID.SOHNUM_0
    END AS SALESORDER,
    CASE
        WHEN SID.SOHNUM_0 = '' THEN (
            SELECT TOP 1 SOH.ORDDAT_0  -- Get ORDDAT_0 here
            FROM LIVE.SORDER SOH
            WHERE SOH.SOHNUM_0 = (
                SELECT TOP 1 SDD.SOHNUM_0
                FROM LIVE.SDELIVERYD SDD
                WHERE SDD.SDHNUM_0 = (
                    SELECT TOP 1 SRD.SDHNUM_0
                    FROM LIVE.SRETURND SRD
                    WHERE SRD.SIHNUM_0 = SID.NUM_0 AND SRD.SIDLIN_0 = SID.SIDLIN_0
                )
                AND SDD.SDDLIN_0 = (
                    SELECT TOP 1 SRD.SDDLIN_0
                    FROM LIVE.SRETURND SRD
                    WHERE SRD.SIHNUM_0 = SID.NUM_0 AND SRD.SIDLIN_0 = SID.SIDLIN_0
                )
            )
        )
        ELSE (SELECT TOP 1 ORDDAT_0 FROM LIVE.SORDER WHERE SOHNUM_0 = SID.SOHNUM_0)  -- Get ORDDAT_0 when SOHNUM_0 is known.
    END AS ORDERDATE,
    ITM.CCE_1 AS FINANCIALCLASS,
    ITM.TCLCOD_0 AS PRODUCTCLASS,
    ATX.TEXTE_0 AS MONKCLASS,
    SID.QTY_0 AS QTY,
    SID.SAU_0 AS UOM,
    SID.GROPRI_0 AS GROSSPRI,
    SID.AMTNOTLIN_0 AS LINAMT,
    SID.PFM_0 AS GPAMOUNT
FROM
    LIVE.SINVOICEV SIV
INNER JOIN
    LIVE.SINVOICED SID ON SIV.NUM_0 = SID.NUM_0
LEFT JOIN
    LIVE.ITMMASTER ITM ON SID.ITMREF_0 = ITM.ITMREF_0
LEFT JOIN
    LIVE.SALESREP REP ON SIV.REP_0 = REP.REPNUM_0
LEFT JOIN
    LIVE.BPCUSTOMER BPC ON SIV.BPRPAY_0 = BPC.BPCNUM_0
LEFT JOIN
    LIVE.ATEXTRA ATX ON ATX.CODFIC_0 = 'ATABDIV'
                     AND ATX.IDENT1_0 = '21'
                     AND ATX.ZONE_0 = 'LNGDES'
                     AND ATX.LANGUE_0 = 'ENG'
                     AND ATX.IDENT2_0 = ITM.TSICOD_1
WHERE
    SID.ITMREF_0 NOT IN (
        SELECT value FROM (VALUES ('/FSCS'), ('/FSCF'), ('/DESIGN-PM'), ('COPYBLOCK'), ('/PACFEE'), ('GIFT'), ('TEXT'), ('LABOUR'), ('TRAVEL')) AS ExcludedItems(value)
    )
    AND SIV.REP_0 NOT IN (
        SELECT value FROM (VALUES ('2206'), ('2204'), ('2221'), ('2224'), ('37'), ('54'), ('75'), ('76'), ('80'), ('85'), ('88'), ('90'), ('2213'), ('SS')) AS ExcludedReps(value)
    )
    AND SIV.SALFCY_0 NOT IN (
        SELECT value FROM (VALUES ('1200'), ('1600'), ('1800'), ('2100'), ('2300'), ('2400'), ('2500'), ('2600'), ('2700'), ('2800')) AS ExcludedSites(value)
    )
    AND SIV.CREDAT_0 >= DATEADD(month, -1, CAST(GETDATE() AS DATE))
;

----------------------

SELECT
SIV.CREDAT_0 AS CREATIONDATE,
SIV.REP_0 AS REPNUM,
(SELECT TOP 1
REP.REPNAM_0
FROM LIVE.SALESREP REP
WHERE REP.REPNUM_0=SIV.REP_0
) AS REPNAME,
SIV.SALFCY_0 AS SALESSITE,
SIV.BPRPAY_0 AS BPRPAY,
(SELECT top 1
BPC.BPCNAM_0 
FROM LIVE.BPCUSTOMER BPC
WHERE BPC.BPCNUM_0=SIV.BPRPAY_0
) AS BPRPAYNAM,
SIV.BPCORD_0 AS SHIPTOCODE,
SIV.BPDNAM_0 AS SHIPTONAM,
SID.ITMREF_0 AS PRODUCTREF,
SID.ITMDES_0 AS PRODUCTDES,
SIV.NUM_0 AS INVOICENUM,
CASE SID.SOHNUM_0
WHEN '' THEN (
SELECT TOP 1
	SOH.SOHNUM_0
FROM 
	LIVE.SORDER SOH
WHERE 
	SOH.SOHNUM_0=
	(
	SELECT TOP 1
		SDD.SOHNUM_0
	FROM
		LIVE.SDELIVERYD SDD
	WHERE
		SDD.SDHNUM_0=
		(
		SELECT TOP 1
			SRD.SDHNUM_0
		FROM
			LIVE.SRETURND SRD
			WHERE SRD.SIHNUM_0=SID.NUM_0 AND SRD.SIDLIN_0=SID.SIDLIN_0
		)
		AND SDD.SDDLIN_0=
				(
		SELECT TOP 1
			SRD.SDDLIN_0
		FROM
			LIVE.SRETURND SRD
			WHERE SRD.SIHNUM_0=SID.NUM_0 AND SRD.SIDLIN_0=SID.SIDLIN_0
		)
	)
)
ELSE SID.SOHNUM_0
END AS SALESORDER,
ITM.CCE_1 AS FINANCIALCLASS,
ITM.TCLCOD_0 AS PRODUCTCLASS,
(SELECT
TEXTE_0
FROM LIVE.ATEXTRA
WHERE CODFIC_0='ATABDIV' 
AND IDENT1_0='21' 
AND ZONE_0='LNGDES' 
AND LANGUE_0='ENG'
and IDENT2_0=ITM.TSICOD_1
) AS MONKCLASS,
SID.QTY_0 AS QTY,
SID.SAU_0 AS UOM,
SID.GROPRI_0 AS GROSSPRI,
SID.AMTNOTLIN_0 AS LINAMT,
SID.PFM_0 AS GPAMOUNT



FROM LIVE.SINVOICEV SIV
LEFT JOIN LIVE.SINVOICED SID ON SIV.NUM_0=SID.NUM_0
LEFT JOIN LIVE.ITMMASTER ITM ON SID.ITMREF_0=ITM.ITMREF_0

WHERE SID.ITMREF_0 NOT IN ('/FSCS','/FSCF','/DESIGN-PM','COPYBLOCK', '/PACFEE','GIFT','TEXT','LABOUR','TRAVEL')
AND SIV.REP_0 NOT IN ('2206','2204','2221','2224','37','54','75','76','80','85','88','90','2213','SS')
AND SIV.SALFCY_0 NOT IN ('1200','1600','1800','2100','2300','2400','2500','2600','2700','2800')
AND SIV.CREDAT_0 >= DATEADD(month, -1, GETDATE())
AND LEFT(SIV.NUM_0,3)='SCM'