SELECT
PTD.CREDAT_0 as [Date Created],
ZRECNAM_0 as [Receiver],
BPS.BPSNUM_0+' '+BPSNAM_0 as [Supplier],
PTD.POHNUM_0 as [Purchase Order],
PTD.PTHNUM_0 as [Receipt],
isnull(PRD.PNHNUM_0,'') as [Purchase Return],
isnull(PNH.ZDEBNUM_0+' '+PNH.ZDEBNUM1_0+' '+PNH.ZDEBNUM2_0+' '+PNH.ZDEBNUM3_0+' '+PNH.ZDEBNUM4_0,'') as [Debit Memo],
PTD.ITMREF_0 as [Product],
ITP.ITMREFBPS_0 as [Supplier Product],
PTD.ITMDES1_0 as [Description],
ZERRQTY_0 as [Quantity],
PTD.PUU_0 as [Unit],
ZERRDES_0 as [Notes],
PTD.AUUID_0 as [UniqueKey]

FROM LIVE.PRECEIPTD PTD
LEFT JOIN LIVE.BPSUPPLIER BPS ON PTD.BPSNUM_0=BPS.BPSNUM_0
LEFT JOIN LIVE.ITMBPS ITP ON PTD.BPSNUM_0=ITP.BPSNUM_0 AND PTD.ITMREF_0=ITP.ITMREF_0
LEFT JOIN LIVE.PRETURND PRD ON PTD.PTHNUM_0=PRD.PTHNUM_0 and PTD.PTDLIN_0=PRD.PTDLIN_0
LEFT JOIN LIVE.PRETURN PNH ON PRD.PNHNUM_0=PNH.PNHNUM_0

Where ZERRQTY_0>0
order by PTD.CREDATTIM_0, PTD.PTHNUM_0, PTD.PTDLIN_0 DESC