SELECT
ITP.ITMREFBPS_0,
PTD.PTHNUM_0,
PTD.PTDLIN_0,
PTD.ITMREF_0,
CAST(PTD.QTYUOM_0 AS INT),
PTD.POHNUM_0,
PTD.BPSINV_0,
ITP.BPSNUM_0+' '+(SELECT BPSNAM_0 FROM LIVE.BPSUPPLIER WHERE BPSNUM_0=ITP.BPSNUM_0),
PTD.VAT_0,
PTD.VAT_1,
cast(PTD.NETPRI_0 as decimal(18,2))

FROM LIVE.PRECEIPTD PTD
LEFT OUTER JOIN LIVE.ITMBPS ITP ON PTD.ITMREF_0=ITP.ITMREF_0 and PTD.BPSNUM_0=ITP.BPSNUM_0
left outer join LIVE.PINVOICED PID ON PTD.PTHNUM_0=PID.PTHNUM_0 and PTD.PTDLIN_0=PID.PTDLIN_0

WHERE PTD.CREDAT_0>=FORMAT(DATEADD(day, -40, GETDATE()), 'yyyyMMdd') and PRHFCY_0='DC30' and PTD.BPSINV_0='V5555' and LEFT(ITP.ITMREF_0,1)<>'/' and ((SELECT
SUM(QTYUOM_0)
FROM LIVE.PINVOICED
WHERE PTHNUM_0=PTD.PTHNUM_0
and PTDLIN_0=PTD.PTDLIN_0
)<PTD.QTYUOM_0 OR(SELECT
SUM(QTYUOM_0)
FROM LIVE.PINVOICED
WHERE PTHNUM_0=PTD.PTHNUM_0
and PTDLIN_0=PTD.PTDLIN_0
) IS NULL)

order by PTD.CREDAT_0,PTHNUM_0,PTDLIN_0 DESC