SELECT DISTINCT
SOH.CREUSR_0,
SOH.YORDSRC_0,
SOH.SOHNUM_0,
SOH.CREDAT_0,
SOH.YSTUNAM_0,
MAX(PRE.PRHNUM_0),
MAX(PRH.YMOPICKER_0),
MAX(PRE.CREDAT_0),
SOQ.ITMREF_0,
CAST(MAX(SOQ.QTYSTU_0) AS INT),
CAST(MAX(PRE.QTYSTU_0) AS INT),
ITM.SAU_0,
DATEDIFF(day,MAX(PRE.CREDAT_0),SOH.CREDAT_0)

FROM LIVE.SORDER SOH
LEFT OUTER JOIN LIVE.SORDERQ SOQ
ON SOH.SOHNUM_0 = SOQ.SOHNUM_0
LEFT OUTER JOIN LIVE.STOPRED PRE
ON UPPER(SOH.YSTUNAM_0) = PRE.ORINUM_0
LEFT OUTER JOIN LIVE.STOPREH PRH
ON PRE.PRHNUM_0 = PRH.PRHNUM_0
LEFT OUTER JOIN LIVE.ITMMASTER ITM
ON SOQ.ITMREF_0 = ITM.ITMREF_0

WHERE
SOH.YORDSRC_0 >= 4
AND
SOH.CREDAT_0 >= '20230101'
AND
((SOQ.ITMREF_0 = PRE.ITMREF_0) OR (PRE.ITMREF_0 IS NULL))
AND
SOH.BETFCY_0 = 1

GROUP BY

SOH.CREUSR_0,
SOH.YORDSRC_0,
SOH.SOHNUM_0,
SOH.CREDAT_0,
SOH.YSTUNAM_0,
SOQ.ITMREF_0,
ITM.SAU_0

ORDER BY SOH.CREDAT_0 DESC