With DEPOS As (
	SELECT
		NUM_0,
		REFINT_0
	FROM LIVE.GACCENTRY
)

SELECT
SIH.CREDAT_0 as [Date],
SIH.BPRPAY_0 as [BP],
SIH.GTE_0 as [Type],
SIH.AMTATI_0 as [Amount],
SIH.NUM_0 as [Invoice],
SIH.PTE_0 as [Term],
SIV.SIHORINUM_0 as [Source],
PYD.NUM_0 as [Accounting Entry],
HAE.NUM_0 as [Payment],
DEP.NUM_0 as [Payment Journal]

FROM LIVE.SINVOICE SIH
LEFT JOIN LIVE.GACCENTRY HAE ON SIH.NUM_0=HAE.NUM_0 AND SIH.GTE_0=HAE.TYP_0
LEFT JOIN LIVE.PAYMENTD PYD ON SIH.NUM_0=PYD.VCRNUM_0
LEFT JOIN LIVE.SINVOICEV SIV ON SIH.NUM_0=SIV.NUM_0
LEFT join DEPOS	DEP ON 'PYH '+PYD.NUM_0=DEP.REFINT_0
WHERE HAE.NUM_0 IS NULL