SELECT
ACC_0 AS 'GENERAL ACCOUNTS',
CONVERT(VARCHAR,ACCDAT_0,101) AS 'ACCOUNTING DATE',
ACCNUM_0 AS 'ACCOUNTING NUMBER',
ACCNUMDOE_0 AS 'COUNTERPART NUMBER',
ACCNUMORI_0 AS 'SOURCE NUMBER',
AMTCUR_0 AS 'ENTRY AMOUNT',
CASE
WHEN AMTFLG_0 = 1 THEN 'NO'
WHEN AMTFLG_0 = 2 THEN 'YES'
ELSE 'NO'
END AS 'FORCED AMOUNT',
AMTLED_0 AS 'LEDGER AMOUNT',
AMTLED1_0 AS 'FORCED FLAG',
AMTVAT_0 AS 'DECLARED AMOUNT',
AUUID_0 AS 'SINGLE IDENTIFIER',
BPR_0 AS 'BP',
CAPFLOTYP_0 AS 'CAPITAL FLOW',
CHK_0 AS 'RECONCILLIATION',
CONVERT(VARCHAR,CHKDAT_0,101) AS 'RECONCILLIATION DATE',
CHRNUM_0 AS 'CHRONO NUMBER',
COA_0 AS 'CHART CODE',
CPY_0 AS 'COMPANY',
CONVERT(VARCHAR,CREDATTIM_0,101) AS 'DATE CREATED',
CREUSR_0 AS 'CREATION USER',
CSLBPR_0 AS 'PARTNER',
CSLCOD_0 AS 'PARTNER CODE',
CSLFLO_0 AS 'FLOW',
CUR_0 AS 'ENTRY CURRENCY',
CURLED_0 AS 'LEDGER CURRENCY',
DES_0 AS 'DESCRIPTION',
DSP_0 AS 'DISTRIBUTION',
EXPNUM_0 AS 'EXPOIRT NUMBER',
FCYLIN_0 AS 'SITE',
FIY_0 AS 'FISCAL YEAR',
CASE
WHEN FLGMTC_0 = 1 THEN 'NO'
WHEN FLGMTC_0 = 2 THEN 'YES'
WHEN FLGMTC_0 = 0 THEN 'NO'
END AS 'MTC FLAG',
FREREF_0 AS 'FREE REFERENCE',
IDTLIN_0 AS 'IDENTIFIER',
LED_0 AS 'LEDGER',
CASE
WHEN LEDTYP_0 = 1 THEN 'LEGAL'
WHEN LEDTYP_0 = 2 THEN 'ANALYTICAL'
WHEN LEDTYP_0 = 3 THEN 'IAS'
WHEN LEDTYP_0 = 4 THEN 'GEN. LEDGER 4'
WHEN LEDTYP_0 = 5 THEN 'GEN. LEDGER 5'
WHEN LEDTYP_0 = 6 THEN 'GEN. LEDGER 6'
WHEN LEDTYP_0 = 7 THEN 'GEN. LEDGER 7'
WHEN LEDTYP_0 = 8 THEN 'GEN. LEDGER 8'
WHEN LEDTYP_0 = 9 THEN 'GEN. LEDGER 9'
WHEN LEDTYP_0 = 10 THEN 'GEN. LEDGER 10'
END AS 'LEDGER TYPE',
LIN_0 AS 'LINE NUMBER',
MRK_0 AS 'MARKING',
MTC_0 AS 'MATCHING',
CONVERT(VARCHAR,MTCDAT_0,101) AS 'MATCH DATE',
CONVERT(VARCHAR,MTCDATMAX_0,101) AS 'MAXIMUM GROUP DATE',
NUM_0 AS 'DOCUMENT NUMBER',
OFFACC_0 AS 'OFFSET',
PER_0 AS 'PERIOD',
PJTLIN_0 AS 'PROJECT',
CAST(QTY_0 AS INT) AS 'QUANTITY',
REFINTLIN_0 AS 'INTERNAL REFERENCE',
SAC_0 AS 'CONTROL',
SNS_0 AS 'SIGN',
STT1_0 AS 'STATISTICS 1',
STT1_0 AS 'STATISTICS 2',
STT1_0 AS 'STATISTICS 3',
TAX_0 AS 'TAX 1',
TAX2_0 AS 'TAX 2',
TAX3_0 AS 'TAX 3',
TYP_0 AS 'TYPE',
UOM_0 AS 'NONFINANCIAL UNIT',
CONVERT(VARCHAR,UPDDATTIM_0,101) AS 'DATE UPDATED',
UPDUSR_0 AS 'LAST MODIFIED BY',
VATDEDRAT_0 AS 'DEDUCTIB PRO RATA',
VATRAT_0 AS 'APPLIED VAT RATE'

FROM LIVE.GACCENTRYD

WHERE ACCDAT_0 BETWEEN '20230701' AND '20230801'