SELECT TOP 1000 GACCENTRY.ACCDAT_0, AMTCUR_0*GACCENTRYD.SNS_0, GACCENTRYD.DES_0, GACCENTRY.REF_0, GACCENTRY.BPRVCR_0 FROM LIVE.GACCENTRY
LEFT OUTER JOIN LIVE.GACCENTRYD ON GACCENTRY.NUM_0 = GACCENTRYD.NUM_0
WHERE LEFT(GACCENTRY.BPRVCR_0, 5) IN ('RECCC', 'RECC1', 'IPIRE', 'IPIEX') AND GACCENTRYD.ACC_0 = 10100

order by GACCENTRY.ACCDAT_0 desc