SELECT
CONVERT(VARCHAR, SIV.CREDAT_0, 101) AS 'DATE CREATED',
SIV.SALFCY_0 AS 'SALES SITE',
SIV.NUM_0 AS 'INVOICE NUMBER',
CASE SIV.SIVTYP_0
WHEN 'INFPC' THEN 'CREDIT MEMO'
WHEN 'CRM' THEN 'CREDIT MEMO'
ELSE 'INVOICE'
END AS 'TYPE',
SIV.BPDPOSCOD_0 AS 'POSTAL CODE',
SIV.BPDCTY_0 AS 'CITY',
CASE SIV.SIHORI_0
WHEN 1 then 'DIRECT'
WHEN 2 then 'ORDER'
WHEN 4 then 'INVOICE'
WHEN 5 THEN 'QUOTE'
WHEN 6 THEN 'RETURN'
WHEN 7 THEN 'SERVICE CONTRACT'
WHEN 8 THEN 'SERVICE REQUEST'
WHEN 9 THEN 'TRANSFER'
WHEN 10 THEN 'SCHED,ULED INVOICE'
END AS 'ORIGIN',
CASE
WHEN SIV.CREUSR_0 = 'YMIRA' THEN 'MIRACLE SERVICE'
WHEN SIV.SALFCY_0 = 'DC30' THEN 'COMMERCIAL'
WHEN SIV.SALFCY_0 = 'DC31' THEN 'FURNITURE'
WHEN SIV.NUM_0 LIKE 'STR%' THEN 'INFOPOS INVOICE'
ELSE 'RETAIL'
END AS 'SOURCE'

FROM LIVE.SINVOICEV SIV

WHERE SIV.SIHORI_0 <> 3 AND SIV.CREDAT_0 BETWEEN '20240401' AND '20240831'

ORDER BY SIV.CREDAT_0, SIV.SALFCY_0 ASC