With LocData AS (
	SELECT
		STO.ITMREF_0,
		STO.LOC_0,
		SUM(CASE WHEN STA_0='A' THEN IVT.PHYSTO_0 ELSE 0 END) AS STA_A,
		SUM(CASE WHEN STA_0='Q' THEN IVT.CTLSTO_0 ELSE 0 END) AS STA_Q,
		SUM(CASE WHEN STA_0='R' THEN IVT.REJSTO_0 ELSE 0 END) AS STA_R
	FROM LIVE.STOCK STO
	LEFT JOIN LIVE.ITMMVT IVT ON STO.ITMREF_0=IVT.ITMREF_0 AND STO.ITMREF_0=IVT.ITMREF_0
	WHERE STO.STOFCY_0='DC30'
	Group by LOC_0,STO.ITMREF_0,STA_0
)

SELECT
ITM.ITMREF_0,
LOC.LOC_0,
LOC.STA_A,
LOC.STA_Q,
LOC.STA_R

FROM LIVE.ITMMASTER ITM
LEFT JOIN LocData LOC ON ITM.ITMREF_0=LOC.ITMREF_0