SELECT 
  DISTINCT LANMES_0, 
  CAST(YEAR(SIH.CREDAT_0) AS VARCHAR) AS [Year], 
  CAST(MONTH(SIH.CREDAT_0) AS VARCHAR) AS [Month], 
  FORMAT(SIH.CREDAT_0, 'MMMM') AS [MonthName], 
  COUNT(SIH.NUM_0) AS [InvoiceCount] 
FROM 
  LIVE.SINVOICE SIH 
  LEFT JOIN LIVE.SINVOICEV SIV ON SIH.NUM_0 = SIV.NUM_0 
  LEFT JOIN LIVE.BPDLVCUST DLV ON SIV.BPCORD_0 = DLV.BPCNUM_0 
  LEFT JOIN LIVE.APLSTD AST ON AST.LANNUM_0 = DLV.DRN_0 
  AND AST.LANCHP_0 = 409 
  AND AST.LAN_0 = 'ENG' 
  LEFT JOIN LIVE.SINVOICED SID ON SIV.NUM_0 = SID.NUM_0 
  LEFT JOIN LIVE.ITMMASTER ITM ON SID.ITMREF_0 = ITM.ITMREF_0 
WHERE 
  AMTATI_0 = 0 
  AND SIH.CREUSR_0 <> 'YMIRA' 
  AND ITM.TSICOD_1 = '3180' 
GROUP BY 
  YEAR(SIH.CREDAT_0), 
  MONTH(SIH.CREDAT_0), 
  FORMAT(SIH.CREDAT_0, 'MMMM'), 
  LANMES_0
