WITH VendorPrice AS (
	SELECT
		ITP.ITMREF_0,
		ITP.BPSNUM_0,
		ROW_NUMBER() OVER (
			PARTITION BY ITP.ITMREF_0 
			ORDER BY ITP.PIO_0 DESC
		) AS RowNum
	FROM
		LIVE.ITMBPS ITP
),
VendorPriceTop AS (
	SELECT
		ITMREF_0,
		BPSNUM_0
	FROM
		VendorPrice
	WHERE
		RowNum = 1
)


SELECT
SIV.CREDAT_0 AS [Date Created],
SIV.INVDAT_0 as [Invoice Date],
SID.REP1_0 AS [Rep],
(SELECT TOP 1
REP.REPNAM_0
FROM LIVE.SALESREP REP
WHERE REP.REPNUM_0=SID.REP1_0
) AS [Rep Name],
SIV.SALFCY_0 AS [Sales Site],
SIV.BPRPAY_0 AS [Pay-by],
(SELECT top 1
BPC.BPCNAM_0 
FROM LIVE.BPCUSTOMER BPC
WHERE BPC.BPCNUM_0=SIV.BPRPAY_0
) AS [Pay-by Name],
SIV.BPCORD_0 AS [Ship-to],
SIV.BPDNAM_0 AS [Ship-to Name],
SID.ITMREF_0 AS [Product],
SID.ITMDES_0 AS [Description],
SIV.NUM_0 AS [Invoice],
CASE SID.SOHNUM_0
WHEN '' THEN (
SELECT TOP 1
	SOH.SOHNUM_0
FROM 
	LIVE.SORDER SOH
WHERE 
	SOH.SOHNUM_0=
	(
	SELECT TOP 1
		SDD.SOHNUM_0
	FROM
		LIVE.SDELIVERYD SDD
	WHERE
		SDD.SDHNUM_0=
		(
		SELECT TOP 1
			SRD.SDHNUM_0
		FROM
			LIVE.SRETURND SRD
			WHERE SRD.SIHNUM_0=SID.NUM_0 AND SRD.SIDLIN_0=SID.SIDLIN_0
		)
		AND SDD.SDDLIN_0=
				(
		SELECT TOP 1
			SRD.SDDLIN_0
		FROM
			LIVE.SRETURND SRD
			WHERE SRD.SIHNUM_0=SID.NUM_0 AND SRD.SIDLIN_0=SID.SIDLIN_0
		)
	)
)
ELSE SID.SOHNUM_0
END AS [Sales Order],
ITM.CCE_1 AS [Financial Class],
ITM.TCLCOD_0 AS [Category],
(SELECT
TEXTE_0
FROM LIVE.ATEXTRA
WHERE CODFIC_0='ATABDIV' 
AND IDENT1_0='21' 
AND ZONE_0='LNGDES' 
AND LANGUE_0='ENG'
and IDENT2_0=ITM.TSICOD_1
) AS [Monk Class],
SID.QTY_0 AS [Quantity],
SID.SAU_0 AS [Unit of Measure],
SID.GROPRI_0*SIH.SNS_0 AS [Sale Price],
SID.CPRPRI_0 AS [Cost Price],
SID.PFM_0*SIH.SNS_0 AS [GP],
SID.AMTNOTLIN_0*SIH.SNS_0 AS [Sale Price Total],
SID.CPRPRI_0*SID.QTY_0*SIH.SNS_0 AS [Cost Price Total],
SID.PFM_0*SIH.SNS_0*SID.QTY_0 AS [GP Total],
isnull((SID.PFM_0 * SIH.SNS_0 * SID.QTY_0) / NULLIF(SID.AMTNOTLIN_0 * SIH.SNS_0, 0),1) AS [GP Total %],
ISNULL(IVT.AVC_0,isnull(PP.PRI_0,0)) as [Current Cost Avg],
ITM.TSICOD_0 as [Current Status]



FROM LIVE.SINVOICEV SIV
LEFT JOIN LIVE.SINVOICED SID ON SIV.NUM_0=SID.NUM_0
LEFT JOIN LIVE.SINVOICE SIH ON SIV.NUM_0=SIH.NUM_0
LEFT JOIN LIVE.ITMMASTER ITM ON SID.ITMREF_0=ITM.ITMREF_0
LEFT JOIN LIVE.ITMMVT IVT ON SID.ITMREF_0=IVT.ITMREF_0 AND IVT.STOFCY_0='DC30'
LEFT JOIN VendorPriceTop VPI ON SID.ITMREF_0 = VPI.ITMREF_0
LEFT JOIN LIVE.PPRICLIST PP ON SID.ITMREF_0 = PP.PLICRI2_0 AND PP.PLICRI1_0 = VPI.BPSNUM_0 AND PP.PLI_0 = 'T20'
WHERE
SID.INVDAT_0 Between '20220701' AND '20221231'
AND SID.GROPRI_0<>0