SELECT 
  PIH.ACCDAT_0, 
  PIH.NUM_0, 
  PIH.BPR_0 + ' - ' + PIH.BPRNAM_0, 
  CASE WHEN PTH.BPSNUM_0 IS NULL THEN PIH.BPR_0 + ' - ' + PIH.BPRNAM_0 ELSE PTH.BPSNUM_0 + ' - ' + BPS.BPSNAM_0 END, 
  PIH.AMTATI_0, 
  SUM(DUD.PAYCUR_0), 
  (
    CASE CAST(
      SUM(DUD.PAYCUR_0) as VARCHAR
    ) WHEN '0.0000000000000' THEN 'Unpaid' ELSE CASE CAST(
      (
        PIH.AMTATI_0 - SUM(DUD.PAYCUR_0)
      ) AS VARCHAR
    ) WHEN '0.0000000000000' THEN 'Paid' ELSE 'Partially Paid' END END
  ) AS STATUS 
FROM 
  LIVE.PINVOICE PIH 
  LEFT OUTER JOIN LIVE.GACCDUDATE DUD ON PIH.NUM_0 = DUD.NUM_0 
  AND PIH.GTE_0 = DUD.TYP_0 
  LEFT OUTER JOIN LIVE.PINVOICED PID ON PIH.NUM_0 = PID.NUM_0 
  and PID.PIDLIN_0 = 1000 
  LEFT OUTER JOIN LIVE.PRECEIPT PTH ON PID.PTHNUM_0 = PTH.PTHNUM_0 
  LEFT OUTER JOIN LIVE.BPSUPPLIER BPS ON PTH.BPSNUM_0 = BPS.BPSNUM_0 
WHERE 
  PIH.GTE_0 <> 'SPMEM' 
  AND (
    DUD.SNS_0 = -1 
    OR DUD.SNS_0 IS NULL
  ) 
  AND PIH.ACCDAT_0 >= '20230701' 
GROUP BY 
  PIH.ACCDAT_0, 
  PIH.NUM_0, 
  PIH.BPR_0, 
  PTH.BPSNUM_0, 
  BPS.BPSNAM_0, 
  PIH.BPRNAM_0, 
  PIH.AMTATI_0 
Order by 
  PIH.ACCDAT_0 DESC
