SELECT
SOH.CREDAT_0,
SOH.SOHNUM_0,
SOH.BPCORD_0,
SOH.BPCNAM_0,
SOQ.ITMREF_0,
ITM.ITMDES1_0+' '+ITM.ITMDES2_0,
cast(SOQ.QTYSTU_0 as int),
cast(SOQ.DLVQTYSTU_0 as int),
cast(SOQ.QTYSTU_0-(SOQ.ALLQTYSTU_0+SOQ.PREQTYSTU_0+SOQ.DLVQTYSTU_0) as int),
cast(SOQ.ALLQTYSTU_0 as int),
cast(SOQ.PREQTYSTU_0 as int),
(SELECT 
TOP 1 POQ.POHNUM_0
FROM 
	LIVE.PORDERQ POQ
WHERE 
	POQ.ITMREF_0 = SOQ.ITMREF_0
	AND left(POQ.POHNUM_0, 3) = 'PO3' 
	AND left(POQ.BPSNUM_0,1) = 'V' 
	AND POQ.LINCLEFLG_0 = 1 
Order by POQ.EXTRCPDAT_0 desc
),
(SELECT 
TOP 1 POQ2.EXTRCPDAT_0
FROM 
	LIVE.PORDERQ POQ2
WHERE 
	POQ2.ITMREF_0 = SOQ.ITMREF_0
	AND left(POQ2.POHNUM_0, 3) = 'PO3' 
	AND left(POQ2.BPSNUM_0,1) = 'V' 
	AND POQ2.LINCLEFLG_0 = 1 
Order by POQ2.EXTRCPDAT_0 desc
)


FROM LIVE.SORDER SOH
LEFT OUTER JOIN LIVE.SORDERQ SOQ ON SOH.SOHNUM_0 = SOQ.SOHNUM_0
LEFT OUTER JOIN LIVE.ITMMASTER ITM ON SOQ.ITMREF_0 = ITM.ITMREF_0

WHERE SOH.ORDSTA_0 = 1 AND SOQ.SOQSTA_0 = 1 AND left(SOH.BPCORD_0,3) = 'ICR'