SELECT
CONVERT(VARCHAR, SEU.CREDATTIM_0, 101),
SEU.BPCNUM_0,
SEU.ACCNCKNAM_0,
SEU.VCRNUM_0,
SIH.PTE_0,
CASE SEU.STAFLG_0
WHEN 1 THEN 'SELECTED'
WHEN 2 THEN 'VERIFIED'
WHEN 3 THEN 'AUTHORIZED'
WHEN 4 THEN 'REJECTED'
WHEN 5 THEN 'VOIDED'
WHEN 6 THEN 'CAPTURED'
WHEN 7 THEN 'SETTLED'
WHEN 8 THEN 'MANUAL'
END,
SEU.ACCL4D_0,
SEU.SOHNUM_0,
SEU.SDHNUM_0,
SEU.SIHNUM_0,
SEU.AUTID_0,
SEU.AUTMSG_0,
SEU.AUTAMT_0,
SEU.ORIGAUTH_0,
SEU.TXNID_0,
SEU.VPSTXID_0,
SEU.VANREF_0

FROM LIVE.SEAUTH SEU 
LEFT OUTER JOIN LIVE.SINVOICE SIH
ON SEU.VCRNUM_0 = SIH.NUM_0
LEFT OUTER JOIN LIVE.SINVOICEV SIV
ON SIH.NUM_0 = SIV.NUM_0



WHERE LEFT(VCRNUM_0,3) IN ('DIR')
AND SIH.CREDAT_0 >= '20250107'
AND SIV.INVSTA_0 = 3
AND SEU.STAFLG_0 in (1,2,3,4,7,8)