SELECT 
  STJ.CREDAT_0, 
  STJ.STOFCY_0, 
  STJ.ITMREF_0, 
  ITM.ITMDES1_0, 
  SUM(STJ.QTYSTU_0), 
  IVT.AVC_0, 
  IVT.AVC_0 * SUM(STJ.QTYSTU_0), 
  STJ.LOC_0, 
  STJ.MVTDES_0, 
  STJ.CREUSR_0 
FROM 
  STOJOU STJ 
  LEFT OUTER JOIN ITMMASTER ITM ON STJ.ITMREF_0 = ITM.ITMREF_0 
  LEFT OUTER JOIN ITMMVT IVT ON STJ.ITMREF_0 = IVT.ITMREF_0 
  AND STJ.STOFCY_0 = IVT.STOFCY_0 
WHERE 
  STJ.VCRTYP_0 = 20 
  AND STJ.CREDAT_0 >= % 1 % 
  AND STJ.CREDAT_0 <= % 2 % 
  AND (
    STJ.MVTDES_0 LIKE 'CHG%' 
    OR STJ.MVTDES_0 LIKE 'MIA%'
  ) 
GROUP BY 
  STJ.CREDAT_0, 
  STJ.STOFCY_0, 
  STJ.ITMREF_0, 
  ITM.ITMDES1_0, 
  STJ.LOC_0, 
  STJ.MVTDES_0, 
  IVT.AVC_0, 
  STJ.CREUSR_0 
HAVING 
  SUM(STJ.QTYSTU_0) < 0 
ORDER BY 
  STJ.CREDAT_0 DESC
