SELECT 
HAE.FIY_0,
HAE.PER_0,
DAE.ACC_0,
DAE.NUM_0,
HAE.REF_0,
RIGHT(HAE.REFINT_0,LEN(HAE.REFINT_0)-4),
PYD.VCRNUM_0,
(
SELECT
HAE2.NUM_0
FROM LIVE.GACCENTRY HAE2
WHERE HAE2.REF_0 = HAE.REF_0 AND HAE2.NUM_0 LIKE 'BANK%' AND HAE2.TYP_0 = 'RECPT'
),
CASE 
WHEN SDH.SOHNUM_0 IS NULL THEN ''
ELSE SDH.SOHNUM_0
END,
DUD.AMTCUR_0*DUD.SNS_0,
DAE.AMTCUR_0*DAE.SNS_0,
HAE.ACCDAT_0

FROM LIVE.GACCENTRYD DAE
LEFT OUTER JOIN LIVE.GACCENTRY HAE ON DAE.NUM_0 = HAE.NUM_0 AND DAE.TYP_0 = HAE.TYP_0
LEFT OUTER JOIN LIVE.PAYMENTD PYD ON RIGHT(HAE.REFINT_0, LEN(HAE.REFINT_0)-4) = PYD.NUM_0
LEFT OUTER JOIN LIVE.SINVOICEV SIV ON PYD.VCRNUM_0 = SIV.NUM_0
LEFT OUTER JOIN LIVE.SDELIVERY SDH ON SIV.SIHORINUM_0 = SDH.SDHNUM_0
LEFT OUTER JOIN LIVE.GACCDUDATE DUD ON SIV.NUM_0 = DUD.NUM_0

WHERE left(HAE.NUM_0,5)='DEPOS' AND HAE.FIY_0 = '25' AND HAE.REFINT_0 <> '' AND DAE.ACC_0 = '10400' AND HAE.CAT_0 = 1