SELECT DISTINCT
SOH.CREDAT_0,
SOH.BPCNAM_0,
SOH.BPCORD_0,
SOQ.ITMREF_0,
SOP.ITMDES_0,
SOQ.QTY_0,
SOP.SAU_0,
(SOP.GROPRI_0*SOQ.QTY_0),
(SOP.GROPRI_0*SOQ.QTY_0*1.12),
SOH.CUSORDREF_0

FROM SORDER SOH

LEFT OUTER JOIN SORDERQ SOQ ON
SOH.SOHNUM_0 = SOQ.SOHNUM_0

LEFT OUTER JOIN SORDERP SOP ON
SOQ.SOHNUM_0 = SOP.SOHNUM_0 AND SOQ.ITMREF_0 = SOP.ITMREF_0

WHERE

SOH.BPCINV_0 = '64' AND SOH.CREDAT_0 >= '20220701'