SELECT 
  BANK.BAN_0, 
  BANK.DES_0, 
  COMPANY.CPYSHO_0, 
  GACCOUNT.ACC_0, 
  AVWTEXTRA.TEXTE_0, 
  BANK.CUR_0, 
  GACCENTRYD.TYP_0, 
  GACCENTRYD.NUM_0 
From 
  LIVE.BANK 
  LEFT OUTER JOIN LIVE.COMPANY ON BANK.CPY_0 = COMPANY.CPY_0 
  LEFT OUTER JOIN LIVE.GACCOUNT ON BANK.COA_0 = GACCOUNT.COA_0 
  AND BANK.BANACC_0 = GACCOUNT.ACC_0 
  LEFT OUTER JOIN LIVE.AVWTEXTRA ON GACCOUNT.COA_0 = AVWTEXTRA.IDENT1_0 
  AND GACCOUNT.ACC_0 = AVWTEXTRA.IDENT2_0 
  LEFT OUTER JOIN LIVE.GACCENTRYD ON GACCOUNT.ACC_0 = GACCENTRYD.ACC_0 
WHERE 
  (
    AVWTEXTRA.ZONE_0 = 'DESTRA' 
    and AVWTEXTRA.CODFIC_0 = 'GACCOUNT' 
    and AVWTEXTRA.LAN_0 = 'ENG'
  ) 
  AND GACCENTRYD.ACCDAT_0 BETWEEN '20230701' 
  AND '20240415' 
  AND BANK.BANCSH_0 = 1 
Order by 
  GACCENTRYD.ACCDAT_0 asc
