SELECT
SDH.CREDAT_0,
SDH.SDHNUM_0,
SDH.BPCINV_0

FROM SDELIVERY SDH
LEFT OUTER JOIN SINVOICE SIH ON SDH.SDHNUM_0 = SIH.NUM_0

WHERE SDH.SDHNUM_0 LIKE 'STR%'

AND SDH.CREDAT_0 >= '20200101'
AND SDH.INVFLG_0 = 1
AND SDH.BPCINV_0 <> 'IMAIN'

Order by SDH.CREDAT_0 desc