SELECT
COUNT(SIH.NUM_0),
BPC.CREDAT_0,
BPC.BPCNUM_0,
BPC.BPCNAM_0,
BPC.BPCSTA_0,
(SELECT TOP 1
CONVERT(VARCHAR, CREDAT_0, 101)
FROM LIVE.SINVOICE
WHERE BPR_0 = BPC.BPCNUM_0
ORDER BY CREDAT_0 DESC
)

FROM LIVE.BPCUSTOMER BPC
LEFT OUTER JOIN LIVE.SINVOICE SIH ON BPC.BPCNUM_0 = SIH.BPR_0

WHERE BPC.BPCNUM_0 like 'TMS%' AND BPC.BPCNUM_0 = 'TMS0090430'

GROUP BY BPC.CREDAT_0,BPC.BPCNUM_0,BPC.BPCNAM_0,BPC.BPCSTA_0

order by BPC.CREDAT_0 DESC