SELECT
DAE.NUM_0,
PYH.NUM_0,
CONVERT(VARCHAR,DAE.ACCDAT_0,101),
PYH.CHQNUM_0,
PYH.AMTCUR_0,
PYH.CUR_0

FROM LIVE.GACCENTRYD DAE


LEFT OUTER JOIN LIVE.PAYMENTH PYH
ON REPLACE(DAE.DES_0, 'Auto Chk ', '') = PYH.NUM_0
WHERE CHARINDEX('PAYAT', DAE.DES_0) > 0 and DAE.ACC_0 = '10100' AND LEFT(DAE.NUM_0, 4) = 'BANK' and DAE.CHK_0 = '' and PYH.CHQNUM_0 IS NOT NULL

ORDER BY DAE.ACCDAT_0 ASC